import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";

const LanguageContext = createContext(null);

const STORAGE_KEY = "finsight-lang";

// Not exported: named non-component exports break Vite Fast Refresh and can white-screen the app.
const dictionaries = {
  tr: {
    navRates: "Kurlar",
    navCompare: "Kıyasla",
    navPricing: "Paketler",
    navBusiness: "İletişim",
    navContact: "İletişim",
    contactPageLead:
      "Size en uygun kanaldan ulaşın: WhatsApp, telefon, e-posta, Instagram ya da partnerlik başvuru formu. En kısa sürede dönüş yapıyoruz.",
    contactOrbitalHint: "Bir kanala tıklayın",
    contactOrbitalResponse: "Yanıt hızı",
    contactOrbitalConnected: "Alternatif kanallar",
    contactOrbitalCopy: "Kopyala",
    contactOrbitalCopied: "Kopyalandı",
    contactChannelWhatsappLabel: "WhatsApp",
    contactChannelWhatsappDesc:
      "En hızlı yol. Kur, paket ve entegrasyon sorularınızı doğrudan yazabilirsiniz.",
    contactChannelWhatsappBadge: "7/24 açık",
    contactChannelWhatsappSpeed: "Dakikalar içinde",
    contactChannelWhatsappAction: "WhatsApp'tan yaz",
    contactChannelInstagramLabel: "Instagram",
    contactChannelInstagramDesc:
      "Güncel kur paylaşımları ve duyurular; mesaj kutusundan da ulaşabilirsiniz.",
    contactChannelInstagramBadge: "Sosyal",
    contactChannelInstagramSpeed: "Aynı gün",
    contactChannelInstagramAction: "Profili aç",
    contactChannelGmailLabel: "Gmail",
    contactChannelGmailDesc: "Sözleşme, fatura ve kurumsal yazışmalar için e-posta adresimiz.",
    contactChannelGmailBadge: "Kurumsal",
    contactChannelGmailSpeed: "1 iş günü",
    contactChannelGmailAction: "E-posta gönder",
    contactChannelPhoneLabel: "Telefon",
    contactChannelPhoneDesc: "Hafta içi 09.00–18.00 arasında doğrudan telefonla ulaşın.",
    contactChannelPhoneBadge: "Mesai içi",
    contactChannelPhoneSpeed: "Anında",
    contactChannelPhoneAction: "Hemen ara",
    contactChannelFormLabel: "Partnerlik formu",
    contactChannelFormDesc:
      "Döviz büronuzu AdaDöviz'de listelemek için kurum bilgilerinizi bırakın.",
    contactChannelFormBadge: "Başvuru",
    contactChannelFormSpeed: "1 iş günü",
    contactChannelFormAction: "Başvuru formuna git",
    cityFilterAll: "Tüm şehirler",
    cityFilterLabel: "Konum",
    compareTitle: "Kur kıyaslama",
    compareLead:
      "En fazla dört döviz bürosunu seçip son 14 günlük alış/satış eğrilerini aynı grafikte görün.",
    compareCurrency: "Para birimi",
    compareSelectHint: "En fazla 4 işletme",
    compareSelected: "seçili",
    compareEmpty: "Kıyaslamak için en az bir işletme seçin.",
    compareChartTitle: "son 14 gün",
    compareToday: "Bugünkü durum",
    compareBusiness: "İşletme",
    compareChange: "14 günlük değişim",
    trendUp: "yükseldi",
    trendDown: "düştü",
    trendFlat: "değişmedi",
    compareMbLine: "MB kuru",
    compareBoth: "Alış + Satış",
    compareLoading: "Grafik verisi yükleniyor…",
    compareError: "Kur geçmişi alınamadı.",
    pricingTitle: "Size uygun paketi bulun",
    pricingLead: "İşletmeniz için doğru aboneliği seçin; başvurun, biz sizi panoya ekleyelim.",
    pricingCycleLabel: "Fatura dönemi",
    pricingMonthly: "Aylık",
    pricingAnnual: "Yıllık",
    pricingAnnualSave: "Yıllık (%{pct} tasarruf)",
    pricingPopular: "En popüler",
    pricingPerMonth: "/ ay",
    pricingPerYear: "/ yıl",
    pricingBilledMonthly: "Aylık faturalandırılır",
    pricingBilledAnnual: "Yıllık faturalandırılır",
    pricingTrialPeriod: "/ {days} gün",
    pricingStarterName: "Deneme",
    pricingStarterBlurb: "Panoyu tanımak isteyen yeni döviz büroları için.",
    pricingStarterBilled: "{days} günlük ücretsiz deneme",
    pricingStarterF1: "{days} gün tam işletme paneli",
    pricingStarterF2: "1 şube",
    pricingStarterF3: "Canlı USD, EUR ve GBP kurları",
    pricingStarterF4: "Alış / satış marjı",
    pricingStarterF5: "Halka açık listelenme",
    pricingStarterCta: "Ücretsiz dene",
    pricingProName: "Abonelik",
    pricingProBlurb: "Büyüyen bürolar ve düzenli kur yayını için.",
    pricingProF1: "Deneme paketindeki her şey",
    pricingProF2: "İşletme paneli: logo, saat, konum",
    pricingProF3: "Şube yönetimi",
    pricingProF4: "Kıyaslama sayfasında görünürlük",
    pricingProF5: "Süre bitince uzatma / yenileme",
    pricingProCta: "Başvur",
    pricingEntName: "Kurumsal",
    pricingEntBlurb: "Birden fazla şubesi olan kurumlar için.",
    pricingEntPrice: "Özel",
    pricingEntBilled: "Size özel şube limiti ve süre",
    pricingEntF1: "Abonelikteki her şey",
    pricingEntF2: "Çoklu şube limiti",
    pricingEntF3: "Öncelikli destek",
    pricingEntF4: "Özel süre ve faturalama",
    pricingEntCta: "Satışla iletişime geç",
    pricingFootnote:
      "Fiyatlar KKTC Merkez Bankası kur panosu aboneliğine aittir. Ücretsiz listelenme süper yönetici onayıyladır.",
    cookieConsentMessage:
      "Size daha iyi bir hizmet sunabilmek ve site trafiğimizi analiz edebilmek için çerezleri kullanıyoruz. Kabul ederek KVKK standartlarına uygun olarak anonim veri işlememize izin vermiş olursunuz.",
    cookieConsentReject: "Reddet",
    cookieConsentAccept: "Kabul Et",
    cookieConsentRegionLabel: "Çerez tercihleri",
    logsTitle: "İşlem geçmişi",
    logsLeadBusiness:
      "Profilinizde, kurlarınızda ve şubelerinizde yapılan tüm değişiklikler burada kayıt altındadır.",
    logsLeadAdmin:
      "Hangi işletme kâr marjını güncelledi, profil fotoğrafını değiştirdi, telefon numarasını güncelledi — hepsi burada.",
    logsAll: "Tüm işlemler",
    logsAllBusinesses: "Tüm işletmeler",
    logsEmpty: "Kayıt bulunamadı.",
    logsColWhen: "Zaman",
    logsColAction: "İşlem",
    logsColBusiness: "İşletme",
    logsColActor: "Kullanıcı",
    logsColDetail: "Ayrıntı",
    logsLoadError: "Loglar alınamadı.",
    logsPage: "Sayfa",
    homeH1: "KKTC Canlı Döviz Kurları",
    homeLead: "Kuzey Kıbrıs döviz bürolarının güncel alış ve satış kurlarını karşılaştırın.",
    homeH2Offices: "Döviz Büroları",
    businessLogin: "İşletme Girişi",
    businessPanel: "İşletme Paneli",
    adminPanel: "Admin Paneli",
    logout: "Çıkış Yap",
    partnership: "Partnerlik",
    marketSummary: "Piyasa Özeti",
    marketSummaryNote: "KKTC Merkez Bankası kurları baz alınarak yapılmıştır.",
    searchBanks: "Büro ara",
    openNow: "Şu An Açık",
    callBtn: "Ara",
    directionsBtn: "Yol tarifi",
    openAnalysis: "analizi aç",
    buyShort: "Alış",
    sellShort: "Satış",
    bestBuy: "En yüksek alış",
    bestSell: "En düşük satış",
    bestBuyShort: "En iyi",
    bestSellShort: "En iyi",
    currencyConverter: "Döviz Çevirici",
    depositCalculator: "Mevduat Getiri Hesaplayıcı",
    loanCalculator: "Kredi Taksit Hesaplayıcı",
    currencyUnit: "Döviz Birimi",
    selectCurrency: "Döviz Seçiniz",
    operationType: "İşlem Türü",
    buy: "Alış",
    sell: "Satış",
    selectBank: "Döviz Bürosu Seç",
    selectBankPlaceholder: "Bir döviz bürosu seçin",
    amountTl: "Tutar (TL)",
    amountCurrency: "Tutar",
    resultBuy: "Alınacak",
    resultSell: "Elde Edilecek TL",
    resultWaiting: "Sonuç bekleniyor",
    sortLabel: "Sırala",
    clearFilters: "Temizle",
    showResults: "Sonuçları göster",
    banksLoading: "Kur listesi yükleniyor…",
    banksWakingTitle: "Sunucu uyanıyor",
    banksWakingBody: "Kurlar birazdan gelecek — bu birkaç saniye sürebilir.",
    banksErrorTitle: "Kur listesi yüklenemedi",
    banksErrorBody: "Bağlantı kurulamadı. Lütfen tekrar deneyin.",
    retry: "Yeniden dene",
    noBanksMatch: "Filtrelere uyan işletme bulunamadı.",
    themeLight: "Açık tema",
    themeDark: "Koyu tema",
    langTr: "TR",
    langEn: "EN",
    sortNearest: "En Yakın Konum",
    sortOpenNow: "Şu An Açık",
    sortNone: "Alfabetik",
    locationShareTitle: "Konum paylaşımı",
    locationShareConfirm:
      "En yakın konum sıralaması için konumunuz paylaşılacaktır. Onaylıyor musunuz?",
    locationShareAllow: "Konumu paylaş",
    locationShareDeny: "Vazgeç",
    locationPermissionRequired:
      "En yakın konum sıralaması için konum bilgilerine onay vermelisiniz.",
    locationUnsupported: "Tarayıcınız konum servisini desteklemiyor.",
    notificationsTitle: "Bildirimler",
    notificationsEmpty: "Henüz bildiriminiz yok.",
    notificationsMarkAllRead: "Tümünü okundu işaretle",
    notifBranchApprovedTitle: "Şube talebi onaylandı",
    notifBranchRejectedTitle: "Şube talebi reddedildi",
    supportButton: "Yardım / Sorun bildir",
    supportTitle: "Yardım / Sorun bildir",
    supportSubjectLabel: "Konu",
    supportSubjectPlaceholder: "Kısa bir başlık",
    supportMessageLabel: "Mesaj",
    supportMessagePlaceholder: "Sorununuzu veya talebinizi olabildiğince ayrıntılı yazın",
    supportSubmit: "Gönder",
    supportSubmitting: "Gönderiliyor…",
    supportSent: "Talebiniz alındı. En kısa sürede dönüş yapılacak.",
    supportError: "Talep gönderilemedi. Lütfen tekrar deneyin.",
    supportMyTickets: "Taleplerim",
    supportNoTickets: "Henüz destek talebiniz yok.",
    supportStatusOpen: "Açık",
    supportStatusAnswered: "Yanıtlandı",
    supportStatusClosed: "Kapalı",
    supportAdminReplyLabel: "Yanıt",
    supportAdminTab: "Destek",
    supportAdminReplyPlaceholder: "İşletmeye yanıtınızı yazın",
    supportAdminSave: "Kaydet",
    supportAdminFrom: "Bildiren",
    supportAdminEmpty: "Destek talebi yok.",
    onboardingTitle: "Kurulumu tamamlayın",
    onboardingSubtitle: "Profiliniz eksiksizse listede daha görünür olursunuz.",
    onboardingLogo: "Logo yükleyin",
    onboardingHours: "Çalışma saatlerini girin",
    onboardingBranch: "En az bir şube ekleyin",
    onboardingContact: "Telefon ve adres bilgisini tamamlayın",
    onboardingMargins: "Kur marjlarını ayarlayın",
    onboardingDismiss: "Gizle",
    opsTitle: "Sistem durumu",
    opsOverallOk: "Her şey yolunda",
    opsOverallWarn: "Dikkat gerektiren durumlar var",
    opsOverallDown: "Acil müdahale gerekiyor",
    opsStatusOk: "Sorun yok",
    opsStatusWarn: "Uyarı",
    opsStatusDown: "Arıza",
    opsStatusUnknown: "Bilinmiyor",
    opsRates: "MB kur çekimi",
    opsDualWrite: "Dual-write kuyruğu",
    opsDrift: "Supabase drift",
    opsSupabase: "Supabase erişimi",
    opsHydrate: "Son hydrate",
    opsAuditChain: "Audit zinciri",
    opsMigrations: "Migration durumu",
    opsExpiring: "Yaklaşan bitişler",
    marketHealthTitle: "Pazar sağlığı",
    marketHealthLoading: "Pazar sağlığı yükleniyor…",
    marketHealthStale: "Bayat marj",
    marketHealthAnomalies: "Kur anomalisi",
    marketHealthUncovered: "Bürosuz şehir",
    marketHealthNoBranch: "Şubesiz büro",
    marketHealthStaleList: "Uzun süredir marj güncellemeyen bürolar",
    marketHealthAllFresh: "Tüm aktif bürolar güncel.",
    marketHealthNeverConfigured: "hiç marj girmemiş",
    marketHealthDaysAgo: "{n} gün önce",
    marketHealthAnomalyList: "Kur sanity-band dışı",
    marketHealthIssueInverted: "alış ≥ satış (ters spread)",
    marketHealthIssueBuyAboveCb: "alış MB kurunun üstünde",
    marketHealthIssueSellBelowCb: "satış MB kurunun altında",
    marketHealthIssueBuyWide: "alış marjı %10'dan geniş",
    marketHealthIssueSellWide: "satış marjı %10'dan geniş",
    marketHealthManualNote:
      "Kur düzeltmek için ilgili işletmeyi 'İşletmeler' sekmesinden düzenleyin.",
    sortGbpBuyHigh: "En Yüksek Alış (GBP)",
    sortGbpBuyLow: "En Düşük Alış (GBP)",
    sortUsdBuyHigh: "En Yüksek Alış (USD)",
    sortUsdBuyLow: "En Düşük Alış (USD)",
    sortUsdSellLow: "En Düşük Satış (USD)",
    sortUsdSellHigh: "En Yüksek Satış (USD)",
    sortEurSellLow: "En Düşük Satış (EUR)",
    sortEurSellHigh: "En Yüksek Satış (EUR)",
    sortGbpSellLow: "En Düşük Satış (GBP)",
    sortGbpSellHigh: "En Yüksek Satış (GBP)",
    sortEurBuyHigh: "En Yüksek Alış (EUR)",
    sortEurBuyLow: "En Düşük Alış (EUR)",
    chartPrevPeriod: "Önceki dönem",
    chartNextPeriod: "Sonraki dönem",
    chartDetailedAnalysis: "Detaylı Analiz",
    chartExpand: "Grafiği büyüt",
    commonClose: "Kapat",
    calcPrincipalTl: "Anapara Tutarı (TL)",
    calcTermType: "Vade Türü",
    calcTermDays: "Vade Süresi (Gün)",
    calcNetReturn: "Net Getiri",
    calcMaturityTotal: "Vade Sonu Toplam",
    calcLoanType: "Kredi Türü",
    calcLoanAmountTl: "Kredi Tutarı (TL)",
    calcTermMonths: "Vade (Ay)",
    calcMonthlyPayment: "Aylık Taksit Tutarı",
    calcTotalRepayment: "Toplam Geri Ödeme",
    logoutInProgress: "Çıkış Yapılıyor...",
    logoutRedirecting: "Anasayfaya yönlendiriliyorsunuz",
    periodHourly: "Saatlik",
    periodDaily: "Günlük",
    periodWeekly: "Haftalık",
    periodMonthly: "Aylık",
    periodYearly: "Yıllık",
    backToDashboard: "Dashboard",
    managementPanel: "Yönetim Paneli",
    lastUpdate: "Son Güncelleme",
    bulletinDate: "Bülten tarihi",
    lastChecked: "Son kontrol",
    rateSource: "KKTC Merkez Bankası",
    bulletinNo: "Duyuru no",
    subscriptionStatus: "Abonelik Durumu",
    remainingSubscription: "Kalan Abonelik Süresi",
    subscriptionExpired: "Süresi Bitti",
    daysUnit: "Gün",
    centralBankRates: "Merkez Bankası Kurları (Salt Okunur)",
    centralBankRatesNote: "Aşağıdaki kurlar KKTC Merkez Bankası XML kaynağından gelmektedir.",
    subscriptionExpiredNotice:
      "Abonelik süreniz dolmuştur. Kâr marjı ayarları yalnızca görüntülenebilir; güncelleme yapılamaz.",
    accountInactiveNotice:
      "Hesabınız pasif. Kur, marj ve şube düzenlemesi kilitlidir. Abonelik uzatma veya yeni şube talebi gönderebilirsiniz.",
    extendSubscriptionBtn: "Aboneliği Uzat / Talep Gönder",
    buyRates: "ALIŞ KURLAR",
    sellRates: "SATIŞ KURLAR",
    centralBankRate: "Merkez Bankası KUR",
    effectiveRate: "Efektif",
    profitType: "Kâr Tipi",
    profitMargin: "Kâr Marjı",
    profitValue: "Kâr Marjı",
    fixedPrice: "Baz Fiyat (TL)",
    percentPrice: "Yüzdesel (%)",
    finalRate: "Final Kur",
    profitTl: "TL Kâr",
    saveMargins: "Kâr Marjlarını Kaydet",
    quickMarginTitle: "Hızlı marj girişi",
    quickMarginHint: "Tek değeri seçilen tarafın tüm para birimlerine uygula, sonra alttan ince ayar yap.",
    quickMarginBuy: "Alış",
    quickMarginSell: "Satış",
    quickMarginAll: "Hepsi",
    quickMarginValue: "Marj",
    quickMarginApply: "Uygula",
    quickMarginRevert: "Son kayıtlıya dön",
    bizAnalyticsTitle: "İşletme analitiği",
    bizAnalytics7d: "7 gün",
    bizAnalytics30d: "30 gün",
    bizAnalyticsLoading: "Analitik yükleniyor…",
    bizAnalyticsEmpty: "Bu dönemde henüz kayıtlı etkileşim yok.",
    bizAnalyticsEvent_view: "Görüntülenme",
    bizAnalyticsEvent_call: "Arama",
    bizAnalyticsEvent_whatsapp: "WhatsApp",
    bizAnalyticsEvent_directions: "Yol tarifi",
    bizAnalyticsByCurrency: "Para birimine göre",
    bizAnalyticsByCity: "Şehre göre",
    saving: "Kaydediliyor...",
    logoutShort: "Çıkış",
    changePassword: "Şifre Değiştir",
    changePasswordTitle: "Şifre Değiştir",
    oldPassword: "Eski Şifre",
    newPassword: "Yeni Şifre",
    confirmPassword: "Yeni Şifre (Tekrar)",
    confirmPasswordAction: "Onayla",
    cancel: "Vazgeç",
    selectBranchPlaceholder: "Şube seçiniz",
    branchPhoneLabel: "Şube Numarası",
    whatsappPhoneLabel: "WhatsApp iletişim numarası",
    selectBranchToEditPhones: "Düzenlemek için önce bir şube seçin.",
    saveBranchPhonesBtn: "Telefonları Kaydet",
    branchNameLabel: "Şube Adı",
    branchNamePlaceholder: "Şube adını girin",
    updateBranchNameHint: "Şube adını güncelle",
    subscriptionStartDate: "Başlangıç tarihi",
    subscriptionListEmpty: "Henüz şube kaydı yok.",
    subscriptionExpiringSoon: "Abonelik Süresi bitiyor",
    saveBranchNameBtn: "Kaydet",
    loadingShort: "Yükleniyor...",
    newBranchRequestBtn: "Yeni Şube Talebi",
    newBranchRequestTitle: "Yeni Şube Talebi",
    newBranchRequestConfirm:
      "Girdiğiniz bilgilerle yeni bir şube talebi oluşturulacak. Kabul ediyor musunuz?",
    newBranchRequestSuccess: "Şube talebiniz iletildi.",
    confirmRequestBtn: "Evet, Talep Oluştur",
    addBranchDirectBtn: "Şube Ekle",
    addBranchDirectTitle: "Yeni Şube Ekle",
    // U-02: Kota altındayken şube DOĞRUDAN eklenir; metin buna göre.
    addBranchDirectConfirm:
      "Bu şube, satın aldığınız şube kotanız dahilinde hemen eklenecek ve yayına alınacak. Onaylıyor musunuz?",
    addBranchDirectSuccess: "Şube eklendi ve yayına alındı.",
    confirmAddBranchBtn: "Evet, Şubeyi Ekle",
    renewBranchRequestBtn: "Yenileme Talebi",
    renewBranchRequestSuccess: "Şube yenileme talebiniz iletildi.",
    renewBranchRequestPending: "Yenileme talebi bekliyor",
    renewBranchRequestConfirm:
      "Bu pasif şube için yöneticiye yenileme talebi gönderilecek. Onaylıyor musunuz?",
    requestTypeNew: "Yeni Şube",
    requestTypeRenew: "Yenileme",
    branchInactiveLabel: "Pasif",
    tabRequests: "Talepler",
    tabSignups: "Kayıt Başvuruları",
    signupAdminEmpty: "Henüz kayıt başvurusu yok.",
    signupAdminApprove: "Onayla",
    signupAdminReject: "Reddet",
    signupAdminApproved: "Başvuru onaylandı, hesap oluşturuldu.",
    signupAdminRejected: "Başvuru reddedildi.",
    signupAdminActionFailed: "İşlem başarısız.",
    signupAdminRejectPrompt: "Ret sebebi (başvurana e-posta ile gider):",
    signupAdminBranchLimit: "Şube",
    requestsEmpty: "Henüz şube talebi yok.",
    requestStatusPending: "Bekliyor",
    requestStatusApproved: "Onaylandı",
    requestStatusRejected: "Reddedildi",
    approveRequestBtn: "Onayla",
    rejectRequestBtn: "Reddet",
    requestBusinessLabel: "İşletme",
    requestCreatedAt: "Talep tarihi",
    branchLocationTitle: "Şube Konumu",
    branchAddressLabel: "Adres",
    branchAddressPlaceholder: "Haritaya tıklayın veya adresi yazın",
    branchMapHint: "Konum seçmek için haritaya tıklayın",
    saveBranchLocationBtn: "Konumu Kaydet",
    saveWorkingHoursBtn: "Saatleri Kaydet",
    passwordMismatch: "Yeni şifreler eşleşmiyor.",
    passwordChangedSuccess: "Şifre başarıyla değiştirildi.",
    footerTagline: "Kuzey Kıbrıs'ın Döviz Adresi",
    dateRangeStart: "Başlangıç",
    dateRangeEnd: "Bitiş",
    /* Sinematik alt bölüm (CinematicFooter). */
    footerCtaHeading: "Bugünün en iyi kurunu bul",
    footerCtaCompare: "Büroları Kıyasla",
    footerCtaPartner: "İşletme Başvurusu",
    footerLive: "Kurlar canlı",
    footerBackTop: "Sayfanın başına dön",
    footerMarquee1: "Canlı kurlar",
    footerMarquee2: "Şeffaf karşılaştırma",
    footerMarquee3: "Lefkoşa · Girne · Mağusa",
    footerMarquee4: "En iyi alış ve satış işaretli",
    footerMarquee5: "Reklamsız",
    partnershipDesc: "AdaDöviz ile iş ortaklığı kurmak için başvuru formunu doldurun. Biz size ulaşalım.",
    partnershipPageLead:
      "Döviz büronuzu AdaDöviz'de listelemek için aşağıdaki formu doldurun; ekibimiz bir iş günü içinde dönüş yapar.",
    institutionName: "Kurum Adı",
    contactPerson: "Yetkili Kişi",
    emailLabel: "E-posta",
    phoneLabel: "Telefon",
    messageLabel: "Mesaj",
    institutionNamePlaceholder: "Örn: Ada Döviz",
    contactPersonPlaceholder: "Örn: Tuna Gül",
    emailPlaceholder: "partner@kurum.com",
    phonePlaceholder: "+90 5XX XXX XX XX",
    messagePlaceholder: "Sözleşme kapsamı ve talebinizi kısaca belirtin...",
    messageTemplatePreviewLabel: "Boş bırakılırsa gönderilecek mesaj",
    phoneIncompleteError: "Lütfen 10 haneli telefon numarasını eksiksiz girin.",
    submitApplication: "Başvuruyu Gönder",
    submitting: "Gönderiliyor...",
    applicationSuccess: "Başvurunuz başarıyla gönderildi. En kısa sürede size dönüş yapacağız.",
    applicationSendFailed: "Gönderme başarısız.",
    signupTitle: "Döviz büronuzu ekleyin",
    signupLead:
      "Büronuzu AdaDöviz'e ekletmek için başvurun. Başvurunuzu inceleyip onayladıktan sonra panel hesabınızı açar, e-posta ile parola belirleme bağlantısı göndeririz.",
    signupInstitution: "Kurum adı",
    signupContact: "Yetkili kişi",
    signupCity: "Şehir",
    signupCityNone: "Seçiniz (isteğe bağlı)",
    signupRateInfo: "Mevcut kur bilginiz (isteğe bağlı)",
    signupRateInfoPlaceholder: "Örn: USD alış 40,10 / satış 40,80",
    signupKvkk:
      "Başvuru bilgilerimin değerlendirme amacıyla işlenmesini kabul ediyorum (KVKK aydınlatma metni).",
    signupKvkkRequired: "Devam etmek için KVKK onayını işaretleyin.",
    signupSubmit: "Başvuruyu gönder",
    signupNote: "Bu form hesap oluşturmaz. Hesabınız yalnızca onaydan sonra açılır.",
    signupError: "Başvuru gönderilemedi. Lütfen daha sonra tekrar deneyin.",
    signupDoneTitle: "Başvurunuz alındı",
    signupDoneBody:
      "Başvurunuzu en kısa sürede inceleyeceğiz. Onaylandığında e-posta ile bilgilendirileceksiniz.",
    signupBackHome: "Ana sayfaya dön",
    signupNoAccount: "Hesabınız yok mu?",
    signupNoAccountCta: "Büronuzu ekletin",
    // P3.2 — kur alarmı (C3)
    rateAlertCta: "Kur alarmı kur",
    rateAlertTitle: "Kur alarmı kur",
    rateAlertLead:
      "Bir eşik belirleyin; KKTC Merkez Bankası kuru o seviyeyi geçtiğinde size e-posta gönderelim.",
    rateAlertDirection: "Alarm yönü",
    rateAlertAbove: "Üstüne çıkınca",
    rateAlertBelow: "Altına inince",
    rateAlertThreshold: "Eşik kur (₺)",
    rateAlertKvkk:
      "E-posta adresimin alarm bildirimi amacıyla işlenmesini kabul ediyorum (KVKK aydınlatma metni).",
    rateAlertKvkkRequired: "Devam etmek için KVKK onayını işaretleyin.",
    rateAlertSubmit: "Alarmı kur",
    rateAlertNote:
      "Onay e-postasındaki bağlantıya tıklayana kadar alarm etkinleşmez. İstediğiniz zaman iptal edebilirsiniz.",
    rateAlertError: "Alarm kurulamadı. Lütfen tekrar deneyin.",
    rateAlertDoneVerify:
      "Onay e-postası gönderildi. Alarmı etkinleştirmek için e-postanızdaki bağlantıya tıklayın.",
    rateAlertDoneAlready: "Bu alarm zaten kurulu ve etkin.",
    rateAlertManageTitle: "Kur alarmlarım",
    rateAlertManageFor: "Alarmlar",
    rateAlertManageEmpty: "Kayıtlı alarmınız yok.",
    rateAlertManageError: "Alarmlar yüklenemedi. Bağlantı geçersiz olabilir.",
    rateAlertVerifiedOk: "Alarmınız etkinleştirildi. Eşik aşılınca e-posta göndereceğiz.",
    rateAlertPendingVerify: "Onay bekliyor",
    rateAlertActiveLabel: "Etkin",
    rateAlertPausedLabel: "Duraklatıldı",
    rateAlertLastFired: "Son tetik",
    rateAlertPause: "Duraklat",
    rateAlertResume: "Sürdür",
    rateAlertRemove: "Sil",
    rateAlertStopAll: "Tüm alarmlarımı durdur",
    rateAlertAdminTitle: "Kur alarmları",
    rateAlertAdminRunCheck: "Şimdi kontrol et",
    rateAlertAdminActive: "Etkin (onaylı)",
    rateAlertAdminPending: "Onay bekleyen",
    rateAlertAdminTotal: "Toplam",
    rateAlertAdminCheckDone: "Kontrol (bakılan / tetik / e-posta)",
    rateAlertAdminRecent: "Son alarmlar",
    businessLoginSubtitle: "Kurum hesabınızla oranlarınızı yönetin",
    usernameLabel: "Giriş ID",
    usernamePlaceholder: "örn: AdaDoviz",
    passwordLabel: "Şifre",
    forgotPassword: "Şifremi Unuttum",
    rememberMe: "Oturumu açık tut",
    loginButton: "Giriş Yap",
    loggingIn: "Giriş yapılıyor...",
    loggingInTitle: "Giriş Yapılıyor...",
    loggingInSubtitle: "Yönlendiriliyorsunuz",
    loginFailed: "Giriş başarısız.",
    forgotPasswordTitle: "Şifremi Unuttum",
    forgotPasswordDesc:
      "Kayıtlı iletişim e-postanızı veya Giriş ID’nizi girin. Bağlantı yalnızca Super Admin’de kayıtlı e-posta adresine gider; spam klasörünü de kontrol edin.",
    emailOrUsername: "E-posta veya Giriş ID",
    emailOrUsernamePlaceholder: "ornek@firma.com veya giris-id",
    send: "Gönder",
    sending: "Gönderiliyor...",
    forgotRequestFailed: "İstek gönderilemedi.",
    resetTitle: "Şifre Sıfırlama",
    resetSubtitle: "Yeni şifrenizi belirleyin",
    resetDoneMsg: "Şifreniz başarıyla güncellendi. Artık yeni şifrenizle giriş yapabilirsiniz.",
    resetBackHome: "Ana Sayfaya Dön",
    resetInvalidLink: "Geçersiz veya eksik sıfırlama bağlantısı.",
    resetNoToken: "Geçersiz sıfırlama bağlantısı. Token bulunamadı.",
    resetTooShort: "Şifre en az 4 karakter olmalıdır.",
    resetMismatch: "Şifreler eşleşmiyor.",
    resetFailed: "Şifre güncellenemedi.",
    resetNewPassword: "Yeni Şifre",
    resetConfirmPassword: "Şifre Tekrar",
    resetUpdating: "Güncelleniyor...",
    resetSubmit: "Şifreyi Güncelle",
    exchangeOfficeNotFound: "Bu döviz bürosu bulunamadı.",
    forgotSuccessDefault:
      "Eğer bu hesap sistemde kayıtlıysa ve iletişim e-postası tanımlıysa, sıfırlama bağlantısı o adrese gönderildi. Gelen kutusu ve spam klasörünü kontrol edin.",
    superAdminTitle: "Super Admin Paneli",
    superAdminSubtitle: "İşletme ve abonelik yönetimi",
    backToDashboardLink: "Dashboard'a Dön",
    logsButton: "Loglar",
    seoButton: "SEO",
    seoModalTitle: "SEO Optimizasyonu",
    seoModalHint:
      "Google’da 1. sıra garanti edilemez. Bu ayarlar arama motorlarının sitenizi doğru anlamasına yardımcı olur (başlık, açıklama, anahtar kelimeler, sitemap).",
    seoSiteName: "Site adı",
    seoTitle: "Sayfa başlığı (title)",
    seoDescription: "Meta açıklama",
    seoKeywords: "Anahtar kelimeler",
    seoCanonical: "Canonical URL",
    seoOgImage: "Sosyal görsel URL (og:image)",
    seoRobots: "Robots",
    seoGeoRegion: "Coğrafi bölge",
    seoGeoPlace: "Konum adı",
    seoFocusQueries: "Hedef arama ifadeleri",
    seoStructuredData: "Yapılandırılmış veri (JSON-LD) açık",
    seoSaveBtn: "SEO Ayarlarını Kaydet",
    seoSavedMsg: "SEO ayarları kaydedildi.",
    seoLoadFailed: "SEO ayarları yüklenemedi.",
    seoSaveFailed: "SEO ayarları kaydedilemedi.",
    tabList: "Mevcut İşletmeler",
    tabHealth: "Sistem Sağlığı",
    /* ⚠️ HATA DÜZELTMESİ (R-01): tahsilat / gelir görünürlüğü geri getirildi. */
    tabRevenue: "Tahsilat",
    revThisMonth: "Bu ay",
    revThisYear: "Bu yıl",
    revTotal: "Toplam tahsilat",
    revPending: "Bekleyen",
    revCount: "Ödeme adedi",
    revByPlan: "Pakete göre dağılım",
    revExpiring: "Süresi yaklaşanlar (30 gün)",
    revExpiringEmpty: "30 gün içinde süresi dolacak abonelik yok.",
    revPlans: "Paketler",
    revApplications: "Ortaklık başvuruları",
    revApplicationsEmpty: "Henüz başvuru yok.",
    revBackfill: "Geçmişten üret",
    revDaysLeft: "gün kaldı",
    revNoData: "Kayıt yok.",
    revNewPayment: "Tahsilat kaydet",
    revBusiness: "İşletme",
    revPlan: "Paket",
    revAmount: "Tutar (₺)",
    revVat: "KDV (₺)",
    revMethod: "Yöntem",
    revSave: "Kaydet",
    revSaved: "Tahsilat kaydedildi.",
    revPickBusiness: "İşletme seçin",
    revPickPlan: "Paket seçin",
    revExpired: "süresi doldu",
    colLastLogin: "Son Giriş",
    healthMonitorTitle: "Sistem Sağlık Monitörü",
    healthMbRates: "Merkez Bankası Kurları",
    healthLastFetch: "Son başarılı çekim",
    healthLastAttempt: "Son deneme",
    healthMbError: "Son hata",
    healthDualWrite: "Dual-write hataları",
    healthDualWriteEmpty: "Kayıtlı dual-write hatası yok.",
    healthDriftTitle: "SQLite ↔ Supabase farkı",
    healthDriftOk: "Limit ve e-posta alanlarında fark yok.",
    healthDriftWarn: "SQLite ile Supabase arasında fark bulundu.",
    healthDriftUnavailable: "Drift kontrolü yapılamadı.",
    auditLogTitle: "Denetim Kaydı",
    auditLogEmpty: "Henüz denetim kaydı yok.",
    auditPasswordReset: "Şifre sıfırlama",
    auditPasswordChange: "Şifre değişikliği",
    auditPasswordResetRequested: "Şifre sıfırlama talebi",
    auditBusinessDelete: "İşletme silindi",
    neverLoggedIn: "Hiç giriş yok",
    tabEdit: "İşletme Düzenle & Abonelik",
    tabCreate: "Yeni İşletme Ekle",
    refresh: "Yenile",
    loadingList: "Liste yükleniyor...",
    noBusinessesYet: "Henüz işletme yok.",
    colId: "ID",
    colLoginId: "Giriş ID",
    colEmail: "E-posta",
    businessName: "İşletme Adı",
    colSubscription: "Abonelik",
    colRemaining: "Şube Sayısı",
    colBranchCount: "Şube Sayısı",
    addSubscriptionBtn: "Abonelik ekle",
    addSubscriptionTitle: "Şube Abonelikleri",
    addSubscriptionHint: "Şube seçip aboneliğini yenileyin, 1 ay uzatın veya pasife alın.",
    noBranchesForSubscription: "Bu işletmeye ait şube bulunamadı.",
    saveBranchSubscriptionBtn: "Abonelik Kaydet",
    branchSubscriptionSaved: "Şube aboneliği güncellendi.",
    branchBasedSubscription: "Şube bazlı",
    extendOneMonthBtn: "+1 Ay Uzat",
    activateBranchBtn: "Şubeyi Aktifleştir",
    deactivateBranchBtn: "Şubeyi Pasife Al",
    branchExtendedOneMonth: "Şube aboneliği 1 ay uzatıldı.",
    branchActivatedMsg: "Şube aktifleştirildi.",
    branchDeactivatedMsg: "Şube pasife alındı.",
    editBusinessTitle: "İşletmeyi Düzenle",
    colRegisteredAt: "Kayıt Tarihi",
    colStatus: "Durum",
    colAction: "İşlem",
    statusActive: "Aktif",
    statusInactive: "Pasif",
    editBtn: "Düzenle",
    deleteBtn: "Sil",
    editSubscriptionTitle: "İşletmeyi Düzenle",
    selectFromListPrompt: "Listeden bir işletmenin Düzenle butonuna tıklayın.",
    loginIdField: "Giriş ID",
    loginIdPlaceholder: "örn: AdaDoviz",
    businessEmailField: "E-posta",
    businessEmailPlaceholder: "ornek@firma.com",
    loginIdEmailField: "Giriş ID",
    newPasswordOptionalField: "Yeni Şifre (boş bırakırsanız değişmez)",
    subscriptionTypeLabel: "ABONELİK TİPİ",
    customDaysLabel: "ÖZEL GÜN (+EKLE / -ÇIKAR)",
    customDaysPlaceholder: "Örn: 15 veya -10",
    currentRemainingLabel: "MEVCUT KALAN",
    afterUpdateLabel: "GÜNCELLEME SONRASI",
    subscriptionPriceLabel: "TUTAR",
    customPriceLabel: "ÖZEL TUTAR (₺)",
    customPricePlaceholder: "Örn: 750",
    unlimitedSubscription: "Sınırsız",
    resetSubscriptionBtn: "Aboneliği Sıfırla",
    saveChangesBtn: "Değişiklikleri Kaydet",
    creatingBtn: "Oluşturuluyor...",
    createBusinessBtn: "İşletmeyi Oluştur",
    subTypeTest: "Test",
    subTypeMonthly: "Aylık",
    subTypeYearly: "Yıllık",
    subTypeManual: "Manuel",
    daysRemainingSuffix: "Kaldı",
    minutesAgoSuffix: "dk önce",
    hoursAgoSuffix: "sa önce",
    daysAgoSuffix: "gün önce",
    justNow: "Az önce",
    systemLogsTitle: "Sistem Logları ve İstatistikler",
    totalUniqueVisitors: "Toplam Tekil Ziyaretçi Sayısı",
    recentInteractions: "Son Kullanıcı Etkileşimleri (Anonim)",
    allBusinesses: "Tüm İşletmeler",
    allCurrencies: "Tüm Dövizler",
    filterCurrencyLabel: "Döviz",
    allActions: "Tüm Aksiyonlar",
    onlyLocationViewers: "Sadece Konum İnceleyenler",
    onlyCurrencyViewers: "Sadece Kur İnceleyenler",
    onlyBusinessViewers: "Sadece İşletme İnceleyenler",
    noAnonymousSessions: "Henüz anonim oturum kaydı yok.",
    noMatchingRecords: "Filtrelere uyan kayıt bulunamadı.",
    anonymousSession: "Anonim oturum",
    estimatedLocation: "Tahmini Konum:",
    viewedBusinesses: "İncelenen İşletmeler:",
    viewedRates: "Bakılan Kurlar:",
    deleteBusinessTitle: "İşletmeyi Sil",
    deleteConfirmTemplate:
      '"{name}" adlı işletmeyi ve bu işletmeye ait tüm verileri kalıcı olarak silmek istediğinize emin misiniz?',
    deleteWarning: "Dikkat: Bu işlem geri alınamaz!",
    cancelAlt: "İptal",
    confirmDeleteBtn: "Evet, Kalıcı Olarak Sil",
    resetSubConfirmText:
      "Bu işletmenin aboneliğini sıfırlayıp pasif duruma çekmek istediğinize emin misiniz? Bu işlem geri alınamaz.",
    confirmResetBtn: "Evet, Sıfırla",
    successTitle: "Başarılı!",
    okBtn: "Tamam",
    changesAppliedMsg: "Değişiklikler başarıyla uygulandı.",
    businessDeletedMsg: "İşletme kalıcı olarak silindi.",
    subscriptionResetMsg: "Abonelik sıfırlandı; işletme pasife alındı.",
    businessCreatedMsg: "Yeni işletme oluşturuldu.",
    businessUpdatedMsg: "İşletme güncellendi.",
    businessesLoadFailedMsg: "İşletmeler yüklenemedi.",
    statusUpdateFailedMsg: "Durum güncellenemedi.",
    businessDeleteFailedMsg: "İşletme silinemedi.",
    creationFailedMsg: "Oluşturma başarısız.",
    updateFailedMsg: "Güncelleme başarısız.",
    resetFailedMsg: "Sıfırlama başarısız.",
    expiredCantActivateMsg: "Süresi bitmiş işletme aktif edilemez. Önce abonelik süresini uzatın.",
    selectFromListFirstMsg: "Önce listeden bir işletme seçin.",
    statsLoadFailedMsg: "İstatistikler alınamadı.",
    activeToggleInactive: "Aktif — pasife al",
    inactiveToggleActive: "Pasif — aktife al",
    expiredToggleTitle: "Süresi bitmiş — önce abonelik süresini uzatın",
    logoUrlFieldNote: "",
    customerLabel: "Müşteri",
    businessWord: "İşletme",
    dateRangeLabel: "Tarih Aralığı",
    dateFromLabel: "Başlangıç",
    dateToLabel: "Bitiş",
    selectBusinessFilter: "İşletme Seçimi",
    actionTypeLabel: "İşlem Tipi",
    actionTypeProfile: "Profil Güncelleme",
    actionTypeMargin: "Kâr Marjı Güncelleme",
    actionTypeBranch: "Şube Yönetimi",
    businessLogsSectionTitle: "İşletme İşlem Kayıtları",
    businessLogsEmpty: "Filtrelere uyan işletme logu bulunamadı.",
    loadingGeneric: "Yükleniyor...",
    selectCurrencyFirst: "Lütfen önce Döviz Birimi seçin",
    selectExchangeOffice: "Bir döviz bürosu seçin",
    enterAmount: "Tutar giriniz",
    selectCurrencyPrompt: "Döviz Seçiniz",
    selectOfficePrompt: "Döviz Bürosu Seçin",
    selectOfficeFirst: "Lütfen önce döviz bürosu seçin",
    enterAmountPrompt: "Dönüştürmek istediğiniz tutarı giriniz",
    currencyOrBranchMissing: "Döviz birimi ya da şube seçilmedi",
    businessChartInsufficientData: "Bu işletme için henüz yeterli veri birikmemiş.",
    businessChartWillBuild: "Kurlar kaydedildikçe grafik otomatik olarak oluşacaktır.",
    branchesLabel: "Şubeler",
    chartTabLabel: "Grafik",
    businessInfoTabLabel: "İşletme Bilgileri",
    addressLabelShort: "Adres",
    phoneLabelShort: "Telefon",
    whatsappLabelShort: "WhatsApp",
    workingHoursLabel: "Çalışma Saatleri",
    workingHoursClosed: "Kapalı",
    workingHoursNotSet: "Belirtilmemiş",
    weeklyHoursTitle: "Haftalık Çalışma Saatleri",
    viewWeeklySchedule: "Haftalık programı gör",
    getDirectionsBtn: "Yol Tarifi Al",
    selectBranchForMap: "Haritada göstermek için bir şube seçin.",
    branchNoCoords: "Bu şube için konum koordinatı tanımlı değil.",
    dayMon: "Pazartesi",
    dayTue: "Salı",
    dayWed: "Çarşamba",
    dayThu: "Perşembe",
    dayFri: "Cuma",
    daySat: "Cumartesi",
    daySun: "Pazar",
    branchesLoading: "Şubeler yükleniyor...",
    branchesEmpty: "Bu işletmeye henüz şube eklenmemiş.",
    branchUsageLabel: "Şube Kullanımı",
    addBranchBtn: "Yeni Şube Ekle",
    branchLimitLabel: "Şube Limiti",
    branchLimitTitle: "Şube Limitine Ulaşıldı",
    branchLimitContactMsg:
      "Yeni şube limiti satın almak / talep etmek için iletişime geçin.",
    businessLedgerTitle: "İşletme Dökümü",
    businessLedgerShort: "İşletme Dökümü",
    subscriptionLedgerTitle: "Abonelik Dökümü",
    subscriptionLedgerShort: "Abonelik Dökümü",
    ledgerAmountLabel: "Tutar",
    ledgerEmpty: "Bu dökümde henüz kayıt yok.",
    chartNoData: "Veri yok",
    chartNoPointsInRange: "Bu aralıkta gösterilecek nokta yok",
    rateLabel: "Kur",
    searchPlaceholder: "Ara",
    noResults: "Sonuç yok",
    navBestRate: "En iyi kur",
    bestRateTitle: "Bugünün en iyi kuru",
    bestRateLead:
      "Para birimini ve işlemi seçin; tutar girerseniz her büronun anlık kuruyla elinize geçecek miktarı görün. Bürolar en iyi kurdan en kötüye sıralanır.",
    bestRateCurrency: "Para birimi",
    bestRateAmountBuy: "Bozduracağınız döviz",
    bestRateAmountSell: "Vereceğiniz TL",
    bestRateAmountHint: "İsteğe bağlı",
    bestRateResultBuy: "Elinize geçecek TL",
    bestRateResultSell: "Elinize geçecek döviz",
    bestRateBestBadge: "En iyi",
    bestRateEmpty: "Bu para birimi için şu an kur veren büro yok.",
    bestRateUpdated: "Son güncelleme",
    navMap: "Harita",
    mapTitle: "Döviz büroları haritası",
    mapLead:
      "KKTC'deki döviz bürolarını haritada görün: anlık USD/EUR/GBP kuru, yol tarifi ve WhatsApp. Konumunuza izin verirseniz en yakınlar öne çıkar.",
    mapOpenNow: "Şu an açık",
    mapClosed: "Kapalı",
    mapNearMe: "Bana en yakın",
    mapLocating: "Konum alınıyor…",
    mapLocateError: "Konum alınamadı. Tarayıcı izinlerini kontrol edin.",
    mapLocateUnsupported: "Tarayıcınız konum servisini desteklemiyor.",
    mapYouAreHere: "Buradasınız",
    mapDirections: "Yol tarifi",
    mapDetail: "Detay",
    mapAllCities: "Tüm şehirler",
    mapEmpty: "Bu filtreyle eşleşen şube yok.",
    mapBranchCount: "{n} şube",
    pwaInstallTitle: "AdaDöviz'i ana ekrana ekle",
    pwaInstallBody: "Tek dokunuşla güncel kurlar — uygulama gibi açılır, mağaza gerekmez.",
    pwaInstallAction: "Ekle",
    pwaInstallDismiss: "Şimdi değil",
  },
  en: {
    navRates: "Rates",
    navCompare: "Compare",
    navPricing: "Pricing",
    navBusiness: "Contact",
    navContact: "Contact",
    contactPageLead:
      "Reach us on whichever channel suits you: WhatsApp, phone, email, Instagram or the partnership form. We'll respond as soon as we can.",
    contactOrbitalHint: "Pick a channel",
    contactOrbitalResponse: "Response speed",
    contactOrbitalConnected: "Other channels",
    contactOrbitalCopy: "Copy",
    contactOrbitalCopied: "Copied",
    contactChannelWhatsappLabel: "WhatsApp",
    contactChannelWhatsappDesc:
      "The fastest route — ask about rates, plans or integration directly.",
    contactChannelWhatsappBadge: "Open 24/7",
    contactChannelWhatsappSpeed: "Within minutes",
    contactChannelWhatsappAction: "Message on WhatsApp",
    contactChannelInstagramLabel: "Instagram",
    contactChannelInstagramDesc:
      "Daily rate posts and announcements; our inbox is open there too.",
    contactChannelInstagramBadge: "Social",
    contactChannelInstagramSpeed: "Same day",
    contactChannelInstagramAction: "Open profile",
    contactChannelGmailLabel: "Gmail",
    contactChannelGmailDesc: "Our email address for contracts, invoices and corporate matters.",
    contactChannelGmailBadge: "Corporate",
    contactChannelGmailSpeed: "1 business day",
    contactChannelGmailAction: "Send an email",
    contactChannelPhoneLabel: "Phone",
    contactChannelPhoneDesc: "Call us directly on weekdays between 09.00 and 18.00.",
    contactChannelPhoneBadge: "Business hours",
    contactChannelPhoneSpeed: "Instant",
    contactChannelPhoneAction: "Call now",
    contactChannelFormLabel: "Partnership form",
    contactChannelFormDesc:
      "Leave your institution's details to list your exchange office on AdaDöviz.",
    contactChannelFormBadge: "Application",
    contactChannelFormSpeed: "1 business day",
    contactChannelFormAction: "Go to the application form",
    cityFilterAll: "All cities",
    cityFilterLabel: "Location",
    compareTitle: "Rate comparison",
    compareLead:
      "Pick up to four exchange offices and see their 14-day buy/sell curves on one chart.",
    compareCurrency: "Currency",
    compareSelectHint: "Up to 4 businesses",
    compareSelected: "selected",
    compareEmpty: "Select at least one business to compare.",
    compareChartTitle: "last 14 days",
    compareToday: "Today",
    compareBusiness: "Business",
    compareChange: "14-day change",
    trendUp: "rose",
    trendDown: "fell",
    trendFlat: "unchanged",
    compareMbLine: "CB rate",
    compareBoth: "Buy + Sell",
    compareLoading: "Loading chart data…",
    compareError: "Could not load rate history.",
    pricingTitle: "Find the Perfect Plan",
    pricingLead: "Pick the subscription that fits your exchange office and start listing on AdaDöviz.",
    pricingCycleLabel: "Billing period",
    pricingMonthly: "Monthly",
    pricingAnnual: "Annual",
    pricingAnnualSave: "Annual (Save {pct}%)",
    pricingPopular: "Most Popular",
    pricingPerMonth: "/ month",
    pricingPerYear: "/ year",
    pricingBilledMonthly: "Billed Monthly",
    pricingBilledAnnual: "Billed Annually",
    pricingTrialPeriod: "/ {days} days",
    pricingStarterName: "Starter",
    pricingStarterBlurb: "Perfect for offices trying the live rates panel.",
    pricingStarterBilled: "{days}-day free trial",
    pricingStarterF1: "{days} days of full business access",
    pricingStarterF2: "1 branch",
    pricingStarterF3: "Live USD, EUR and GBP rates",
    pricingStarterF4: "Buy / sell margins",
    pricingStarterF5: "Public listing",
    pricingStarterCta: "Start Free Trial",
    pricingProName: "Professional",
    pricingProBlurb: "Ideal for growing offices that publish rates every day.",
    pricingProF1: "Everything in Starter",
    pricingProF2: "Business panel: logo, hours, map",
    pricingProF3: "Branch management",
    pricingProF4: "Listed on the compare page",
    pricingProF5: "Renew before the period ends",
    pricingProCta: "Get Started",
    pricingEntName: "Enterprise",
    pricingEntBlurb: "For organisations with several branches.",
    pricingEntPrice: "Custom",
    pricingEntBilled: "Custom branch limit and term",
    pricingEntF1: "Everything in Professional",
    pricingEntF2: "Multi-branch limit",
    pricingEntF3: "Priority support",
    pricingEntF4: "Custom term and invoicing",
    pricingEntCta: "Contact Sales",
    pricingFootnote:
      "Prices are for the AdaDöviz live-rates panel. Complimentary listing is granted by a super admin.",
    cookieConsentMessage:
      "We use cookies to improve your experience and analyse site traffic. By accepting, you allow anonymous data processing in line with GDPR/KVKK standards.",
    cookieConsentReject: "Reject",
    cookieConsentAccept: "Accept",
    cookieConsentRegionLabel: "Cookie preferences",
    logsTitle: "Activity log",
    logsLeadBusiness:
      "Every change to your profile, rates and branches is recorded here.",
    logsLeadAdmin:
      "Which business updated its margin, changed its logo, updated its phone number — all here.",
    logsAll: "All actions",
    logsAllBusinesses: "All businesses",
    logsEmpty: "No records found.",
    logsColWhen: "Time",
    logsColAction: "Action",
    logsColBusiness: "Business",
    logsColActor: "User",
    logsColDetail: "Detail",
    logsLoadError: "Could not load logs.",
    logsPage: "Page",
    homeH1: "KKTC Live Exchange Rates",
    homeLead: "Compare live buy and sell rates from Northern Cyprus exchange offices.",
    homeH2Offices: "Exchange Offices",
    businessLogin: "Business Login",
    businessPanel: "Business Panel",
    adminPanel: "Admin Panel",
    logout: "Log Out",
    partnership: "Partnership",
    marketSummary: "Market Summary",
    marketSummaryNote: "Based on Central Bank of Northern Cyprus rates.",
    searchBanks: "Search offices",
    openNow: "Open Now",
    callBtn: "Call",
    directionsBtn: "Directions",
    openAnalysis: "open analysis",
    buyShort: "Buy",
    sellShort: "Sell",
    bestBuy: "Highest buy",
    bestSell: "Lowest sell",
    bestBuyShort: "Best",
    bestSellShort: "Best",
    currencyConverter: "Currency Converter",
    depositCalculator: "Deposit Return Calculator",
    loanCalculator: "Loan Installment Calculator",
    currencyUnit: "Currency",
    selectCurrency: "Select Currency",
    operationType: "Operation",
    buy: "Buy",
    sell: "Sell",
    selectBank: "Select Exchange Office",
    selectBankPlaceholder: "Select an exchange office",
    amountTl: "Amount (TRY)",
    amountCurrency: "Amount",
    resultBuy: "You get",
    resultSell: "You get TRY",
    resultWaiting: "Waiting for result",
    sortLabel: "Sort by",
    clearFilters: "Clear",
    showResults: "Show results",
    banksLoading: "Loading rates…",
    banksWakingTitle: "Server is waking up",
    banksWakingBody: "Rates will appear shortly — this can take a few seconds.",
    banksErrorTitle: "Couldn't load the rate list",
    banksErrorBody: "We couldn't reach the server. Please try again.",
    retry: "Try again",
    noBanksMatch: "No businesses match the filters.",
    themeLight: "Light theme",
    themeDark: "Dark theme",
    langTr: "TR",
    langEn: "EN",
    sortNearest: "Nearest Location",
    sortOpenNow: "Open Now",
    sortNone: "Alphabetical",
    locationShareTitle: "Share location",
    locationShareConfirm:
      "Your location will be shared to sort by nearest location. Do you approve?",
    locationShareAllow: "Share location",
    locationShareDeny: "Cancel",
    locationPermissionRequired:
      "You must allow location access to sort by nearest location.",
    locationUnsupported: "Your browser does not support location services.",
    notificationsTitle: "Notifications",
    notificationsEmpty: "You have no notifications yet.",
    notificationsMarkAllRead: "Mark all as read",
    notifBranchApprovedTitle: "Branch request approved",
    notifBranchRejectedTitle: "Branch request rejected",
    supportButton: "Help / Report an issue",
    supportTitle: "Help / Report an issue",
    supportSubjectLabel: "Subject",
    supportSubjectPlaceholder: "A short title",
    supportMessageLabel: "Message",
    supportMessagePlaceholder: "Describe your issue or request in as much detail as possible",
    supportSubmit: "Send",
    supportSubmitting: "Sending…",
    supportSent: "Your request has been received. We'll get back to you shortly.",
    supportError: "Could not send the request. Please try again.",
    supportMyTickets: "My requests",
    supportNoTickets: "You have no support requests yet.",
    supportStatusOpen: "Open",
    supportStatusAnswered: "Answered",
    supportStatusClosed: "Closed",
    supportAdminReplyLabel: "Reply",
    supportAdminTab: "Support",
    supportAdminReplyPlaceholder: "Write your reply to the business",
    supportAdminSave: "Save",
    supportAdminFrom: "Reported by",
    supportAdminEmpty: "No support requests.",
    onboardingTitle: "Complete your setup",
    onboardingSubtitle: "A complete profile ranks better in the listings.",
    onboardingLogo: "Upload a logo",
    onboardingHours: "Set your working hours",
    onboardingBranch: "Add at least one branch",
    onboardingContact: "Add phone and address details",
    onboardingMargins: "Set your exchange-rate margins",
    onboardingDismiss: "Dismiss",
    opsTitle: "System status",
    opsOverallOk: "All systems normal",
    opsOverallWarn: "Some items need attention",
    opsOverallDown: "Immediate action required",
    opsStatusOk: "OK",
    opsStatusWarn: "Warning",
    opsStatusDown: "Down",
    opsStatusUnknown: "Unknown",
    opsRates: "Central-bank rate fetch",
    opsDualWrite: "Dual-write queue",
    opsDrift: "Supabase drift",
    opsSupabase: "Supabase reachability",
    opsHydrate: "Last hydrate",
    opsAuditChain: "Audit chain",
    opsMigrations: "Migration status",
    opsExpiring: "Upcoming expirations",
    marketHealthTitle: "Market health",
    marketHealthLoading: "Loading market health…",
    marketHealthStale: "Stale margin",
    marketHealthAnomalies: "Rate anomaly",
    marketHealthUncovered: "City with no office",
    marketHealthNoBranch: "Office with no branch",
    marketHealthStaleList: "Offices that haven't updated margins in a while",
    marketHealthAllFresh: "All active offices are current.",
    marketHealthNeverConfigured: "never set a margin",
    marketHealthDaysAgo: "{n} days ago",
    marketHealthAnomalyList: "Outside the rate sanity band",
    marketHealthIssueInverted: "buy ≥ sell (inverted spread)",
    marketHealthIssueBuyAboveCb: "buy above central-bank rate",
    marketHealthIssueSellBelowCb: "sell below central-bank rate",
    marketHealthIssueBuyWide: "buy margin wider than 10%",
    marketHealthIssueSellWide: "sell margin wider than 10%",
    marketHealthManualNote: "To correct a rate, edit the office from the 'Businesses' tab.",
    sortGbpBuyHigh: "Highest Buy (GBP)",
    sortGbpBuyLow: "Lowest Buy (GBP)",
    sortUsdBuyHigh: "Highest Buy (USD)",
    sortUsdBuyLow: "Lowest Buy (USD)",
    sortUsdSellLow: "Lowest Sell (USD)",
    sortUsdSellHigh: "Highest Sell (USD)",
    sortEurSellLow: "Lowest Sell (EUR)",
    sortEurSellHigh: "Highest Sell (EUR)",
    sortGbpSellLow: "Lowest Sell (GBP)",
    sortGbpSellHigh: "Highest Sell (GBP)",
    sortEurBuyHigh: "Highest Buy (EUR)",
    sortEurBuyLow: "Lowest Buy (EUR)",
    chartPrevPeriod: "Previous period",
    chartNextPeriod: "Next period",
    chartDetailedAnalysis: "Detailed Analysis",
    chartExpand: "Expand chart",
    commonClose: "Close",
    calcPrincipalTl: "Principal Amount (TL)",
    calcTermType: "Term Type",
    calcTermDays: "Term Length (Days)",
    calcNetReturn: "Net Return",
    calcMaturityTotal: "Total at Maturity",
    calcLoanType: "Loan Type",
    calcLoanAmountTl: "Loan Amount (TL)",
    calcTermMonths: "Term (Months)",
    calcMonthlyPayment: "Monthly Instalment",
    calcTotalRepayment: "Total Repayment",
    logoutInProgress: "Signing Out...",
    logoutRedirecting: "Redirecting you to the home page",
    periodHourly: "Hourly",
    periodDaily: "Daily",
    periodWeekly: "Weekly",
    periodMonthly: "Monthly",
    periodYearly: "Yearly",
    backToDashboard: "Dashboard",
    managementPanel: "Management Panel",
    lastUpdate: "Last Update",
    bulletinDate: "Bulletin date",
    lastChecked: "Last checked",
    rateSource: "Central Bank of the TRNC",
    bulletinNo: "Bulletin no",
    subscriptionStatus: "Subscription Status",
    remainingSubscription: "Remaining Subscription",
    subscriptionExpired: "Expired",
    daysUnit: "Days",
    centralBankRates: "Central Bank Rates (Read-only)",
    centralBankRatesNote: "The rates below are sourced from the TRNC Central Bank XML feed.",
    subscriptionExpiredNotice:
      "Your subscription has expired. Margin settings are view-only and cannot be updated.",
    accountInactiveNotice:
      "Your account is inactive. Rate, margin and branch edits are locked. You can still request a subscription renewal or a new branch.",
    extendSubscriptionBtn: "Extend Subscription / Send Request",
    buyRates: "BUY RATES",
    sellRates: "SELL RATES",
    centralBankRate: "Central Bank Rate",
    effectiveRate: "Effective",
    profitType: "Profit Type",
    profitMargin: "Profit Margin",
    profitValue: "Profit Margin",
    fixedPrice: "Fixed (TRY)",
    percentPrice: "Percent (%)",
    finalRate: "Final Rate",
    profitTl: "TRY Profit",
    saveMargins: "Save Profit Margins",
    quickMarginTitle: "Quick margin entry",
    quickMarginHint: "Apply one value to every currency on the chosen side, then fine-tune below.",
    quickMarginBuy: "Buy",
    quickMarginSell: "Sell",
    quickMarginAll: "All",
    quickMarginValue: "Margin",
    quickMarginApply: "Apply",
    quickMarginRevert: "Back to last saved",
    bizAnalyticsTitle: "Business analytics",
    bizAnalytics7d: "7 days",
    bizAnalytics30d: "30 days",
    bizAnalyticsLoading: "Loading analytics…",
    bizAnalyticsEmpty: "No recorded interactions in this period yet.",
    bizAnalyticsEvent_view: "Views",
    bizAnalyticsEvent_call: "Calls",
    bizAnalyticsEvent_whatsapp: "WhatsApp",
    bizAnalyticsEvent_directions: "Directions",
    bizAnalyticsByCurrency: "By currency",
    bizAnalyticsByCity: "By city",
    saving: "Saving...",
    logoutShort: "Log Out",
    changePassword: "Change Password",
    changePasswordTitle: "Change Password",
    oldPassword: "Current Password",
    newPassword: "New Password",
    confirmPassword: "Confirm New Password",
    confirmPasswordAction: "Confirm",
    cancel: "Cancel",
    selectBranchPlaceholder: "Select branch",
    branchPhoneLabel: "Branch Number",
    whatsappPhoneLabel: "WhatsApp contact number",
    selectBranchToEditPhones: "Select a branch first to edit.",
    saveBranchPhonesBtn: "Save Phones",
    branchNameLabel: "Branch Name",
    branchNamePlaceholder: "Enter branch name",
    updateBranchNameHint: "Update branch name",
    subscriptionStartDate: "Start date",
    subscriptionListEmpty: "No branches yet.",
    subscriptionExpiringSoon: "Subscription expiring",
    saveBranchNameBtn: "Save",
    loadingShort: "Loading...",
    newBranchRequestBtn: "New branch request",
    newBranchRequestTitle: "New Branch Request",
    newBranchRequestConfirm:
      "A new branch request will be created with the details you entered. Do you accept?",
    newBranchRequestSuccess: "Your branch request has been submitted.",
    confirmRequestBtn: "Yes, Create Request",
    addBranchDirectBtn: "Add Branch",
    addBranchDirectTitle: "Add New Branch",
    addBranchDirectConfirm:
      "This branch is within your purchased branch quota and will be added and published right away. Confirm?",
    addBranchDirectSuccess: "Branch added and published.",
    confirmAddBranchBtn: "Yes, Add Branch",
    renewBranchRequestBtn: "Renewal Request",
    renewBranchRequestSuccess: "Your branch renewal request has been submitted.",
    renewBranchRequestPending: "Renewal request pending",
    renewBranchRequestConfirm:
      "A renewal request for this inactive branch will be sent to the admin. Do you confirm?",
    requestTypeNew: "New branch",
    requestTypeRenew: "Renewal",
    branchInactiveLabel: "Inactive",
    tabRequests: "Requests",
    tabSignups: "Signup Requests",
    signupAdminEmpty: "No signup requests yet.",
    signupAdminApprove: "Approve",
    signupAdminReject: "Reject",
    signupAdminApproved: "Application approved, account created.",
    signupAdminRejected: "Application rejected.",
    signupAdminActionFailed: "Action failed.",
    signupAdminRejectPrompt: "Reason for rejection (emailed to the applicant):",
    signupAdminBranchLimit: "Branch",
    requestsEmpty: "No branch requests yet.",
    requestStatusPending: "Pending",
    requestStatusApproved: "Approved",
    requestStatusRejected: "Rejected",
    approveRequestBtn: "Approve",
    rejectRequestBtn: "Reject",
    requestBusinessLabel: "Business",
    requestCreatedAt: "Request date",
    branchLocationTitle: "Branch Location",
    branchAddressLabel: "Address",
    branchAddressPlaceholder: "Click the map or type an address",
    branchMapHint: "Click the map to pick a location",
    saveBranchLocationBtn: "Save Location",
    saveWorkingHoursBtn: "Save Hours",
    passwordMismatch: "New passwords do not match.",
    passwordChangedSuccess: "Password changed successfully.",
    footerTagline: "Northern Cyprus's Currency Address",
    dateRangeStart: "Start",
    dateRangeEnd: "End",
    /* Sinematik alt bölüm (CinematicFooter). */
    footerCtaHeading: "Find today's best rate",
    footerCtaCompare: "Compare Offices",
    footerCtaPartner: "Business Application",
    footerLive: "Rates are live",
    footerBackTop: "Back to top",
    footerMarquee1: "Live rates",
    footerMarquee2: "Transparent comparison",
    footerMarquee3: "Nicosia · Kyrenia · Famagusta",
    footerMarquee4: "Best buy and sell flagged",
    footerMarquee5: "No ads",
    partnershipDesc: "Fill out the application form to become a partner with AdaDöviz. We'll get in touch with you.",
    partnershipPageLead:
      "Fill in the form below to list your exchange office on AdaDöviz; our team replies within one business day.",
    institutionName: "Institution Name",
    contactPerson: "Contact Person",
    emailLabel: "Email",
    phoneLabel: "Phone",
    messageLabel: "Message",
    institutionNamePlaceholder: "e.g. Ada Döviz",
    contactPersonPlaceholder: "e.g. Tuna Gül",
    emailPlaceholder: "partner@company.com",
    phonePlaceholder: "+90 5XX XXX XX XX",
    messagePlaceholder: "Briefly describe your request and scope of partnership...",
    messageTemplatePreviewLabel: "Message that will be sent if left empty",
    phoneIncompleteError: "Please enter the full 10-digit phone number.",
    submitApplication: "Submit Application",
    submitting: "Submitting...",
    applicationSuccess: "Your application has been submitted successfully. We'll get back to you shortly.",
    applicationSendFailed: "Submission failed.",
    signupTitle: "List your exchange office",
    signupLead:
      "Apply to add your office to AdaDöviz. Once we review and approve your request, we open your panel account and email you a link to set a password.",
    signupInstitution: "Business name",
    signupContact: "Contact person",
    signupCity: "City",
    signupCityNone: "Select (optional)",
    signupRateInfo: "Your current rates (optional)",
    signupRateInfoPlaceholder: "e.g. USD buy 40.10 / sell 40.80",
    signupKvkk:
      "I consent to my application details being processed for evaluation (privacy notice).",
    signupKvkkRequired: "Please tick the consent box to continue.",
    signupSubmit: "Send application",
    signupNote: "This form does not create an account. Your account opens only after approval.",
    signupError: "Could not send the application. Please try again later.",
    signupDoneTitle: "Application received",
    signupDoneBody:
      "We'll review your application as soon as possible. You'll be notified by email once it's approved.",
    signupBackHome: "Back to home",
    signupNoAccount: "Don't have an account?",
    signupNoAccountCta: "List your office",
    // P3.2 — rate alerts (C3)
    rateAlertCta: "Set a rate alert",
    rateAlertTitle: "Set a rate alert",
    rateAlertLead:
      "Pick a threshold and we'll email you when the TRNC Central Bank rate crosses it.",
    rateAlertDirection: "Alert when",
    rateAlertAbove: "Rises above",
    rateAlertBelow: "Falls below",
    rateAlertThreshold: "Threshold rate (₺)",
    rateAlertKvkk:
      "I consent to my email being processed to send alert notifications (privacy notice).",
    rateAlertKvkkRequired: "Please tick the consent box to continue.",
    rateAlertSubmit: "Create alert",
    rateAlertNote:
      "The alert stays inactive until you click the link in the confirmation email. You can cancel any time.",
    rateAlertError: "Could not create the alert. Please try again.",
    rateAlertDoneVerify:
      "Confirmation email sent. Click the link in your email to activate the alert.",
    rateAlertDoneAlready: "This alert is already set up and active.",
    rateAlertManageTitle: "My rate alerts",
    rateAlertManageFor: "Alerts",
    rateAlertManageEmpty: "You have no saved alerts.",
    rateAlertManageError: "Could not load alerts. The link may be invalid.",
    rateAlertVerifiedOk: "Your alert is active. We'll email you when the threshold is crossed.",
    rateAlertPendingVerify: "Pending confirmation",
    rateAlertActiveLabel: "Active",
    rateAlertPausedLabel: "Paused",
    rateAlertLastFired: "Last triggered",
    rateAlertPause: "Pause",
    rateAlertResume: "Resume",
    rateAlertRemove: "Delete",
    rateAlertStopAll: "Stop all my alerts",
    rateAlertAdminTitle: "Rate alerts",
    rateAlertAdminRunCheck: "Check now",
    rateAlertAdminActive: "Active (verified)",
    rateAlertAdminPending: "Pending",
    rateAlertAdminTotal: "Total",
    rateAlertAdminCheckDone: "Check (scanned / fired / emailed)",
    rateAlertAdminRecent: "Recent alerts",
    businessLoginSubtitle: "Manage your rates with your business account",
    usernameLabel: "Login ID",
    usernamePlaceholder: "e.g. AdaDoviz",
    passwordLabel: "Password",
    forgotPassword: "Forgot Password",
    rememberMe: "Keep me signed in",
    loginButton: "Log In",
    loggingIn: "Logging in...",
    loggingInTitle: "Logging In...",
    loggingInSubtitle: "You are being redirected",
    loginFailed: "Login failed.",
    forgotPasswordTitle: "Forgot Password",
    forgotPasswordDesc:
      "Enter your registered contact email or Login ID. The reset link is sent only to the email stored by Super Admin — check spam too.",
    emailOrUsername: "Email or Login ID",
    emailOrUsernamePlaceholder: "example@company.com or login-id",
    send: "Send",
    sending: "Sending...",
    forgotRequestFailed: "Request failed.",
    resetTitle: "Reset Password",
    resetSubtitle: "Set your new password",
    resetDoneMsg: "Your password has been updated. You can now sign in with your new password.",
    resetBackHome: "Back to home",
    resetInvalidLink: "Invalid or missing reset link.",
    resetNoToken: "Invalid reset link. Token not found.",
    resetTooShort: "Password must be at least 4 characters.",
    resetMismatch: "Passwords do not match.",
    resetFailed: "Could not update the password.",
    resetNewPassword: "New Password",
    resetConfirmPassword: "Confirm Password",
    resetUpdating: "Updating...",
    resetSubmit: "Update Password",
    exchangeOfficeNotFound: "This exchange office could not be found.",
    forgotSuccessDefault:
      "If this account exists and has a contact email on file, a reset link was sent there. Check inbox and spam.",
    superAdminTitle: "Super Admin Panel",
    superAdminSubtitle: "Business & subscription management",
    backToDashboardLink: "Back to Dashboard",
    logsButton: "Logs",
    seoButton: "SEO",
    seoModalTitle: "SEO Optimization",
    seoModalHint:
      "A #1 Google ranking cannot be guaranteed. These settings help search engines understand your site (title, description, keywords, sitemap).",
    seoSiteName: "Site name",
    seoTitle: "Page title",
    seoDescription: "Meta description",
    seoKeywords: "Keywords",
    seoCanonical: "Canonical URL",
    seoOgImage: "Social image URL (og:image)",
    seoRobots: "Robots",
    seoGeoRegion: "Geo region",
    seoGeoPlace: "Place name",
    seoFocusQueries: "Target search queries",
    seoStructuredData: "Structured data (JSON-LD) enabled",
    seoSaveBtn: "Save SEO Settings",
    seoSavedMsg: "SEO settings saved.",
    seoLoadFailed: "Failed to load SEO settings.",
    seoSaveFailed: "Failed to save SEO settings.",
    tabList: "Current Businesses",
    tabHealth: "System Health",
    /* R-01 */
    tabRevenue: "Revenue",
    revThisMonth: "This month",
    revThisYear: "This year",
    revTotal: "Total collected",
    revPending: "Pending",
    revCount: "Payments",
    revByPlan: "By plan",
    revExpiring: "Expiring soon (30 days)",
    revExpiringEmpty: "No subscriptions expiring in the next 30 days.",
    revPlans: "Plans",
    revApplications: "Partnership applications",
    revApplicationsEmpty: "No applications yet.",
    revBackfill: "Backfill from history",
    revDaysLeft: "days left",
    revNoData: "No records.",
    revNewPayment: "Record a payment",
    revBusiness: "Business",
    revPlan: "Plan",
    revAmount: "Amount (₺)",
    revVat: "VAT (₺)",
    revMethod: "Method",
    revSave: "Save",
    revSaved: "Payment recorded.",
    revPickBusiness: "Select a business",
    revPickPlan: "Select a plan",
    revExpired: "expired",
    colLastLogin: "Last Login",
    healthMonitorTitle: "System Health Monitor",
    healthMbRates: "Central Bank Rates",
    healthLastFetch: "Last successful fetch",
    healthLastAttempt: "Last attempt",
    healthMbError: "Last error",
    healthDualWrite: "Dual-write errors",
    healthDualWriteEmpty: "No dual-write errors recorded.",
    healthDriftTitle: "SQLite ↔ Supabase drift",
    healthDriftOk: "No differences in limit or email fields.",
    healthDriftWarn: "Differences found between SQLite and Supabase.",
    healthDriftUnavailable: "Drift check could not run.",
    auditLogTitle: "Audit Log",
    auditLogEmpty: "No audit events yet.",
    auditPasswordReset: "Password reset",
    auditPasswordChange: "Password change",
    auditPasswordResetRequested: "Password reset requested",
    auditBusinessDelete: "Business deleted",
    neverLoggedIn: "Never logged in",
    tabEdit: "Edit Business & Subscription",
    tabCreate: "Add New Business",
    refresh: "Refresh",
    loadingList: "Loading list...",
    noBusinessesYet: "No businesses yet.",
    colId: "ID",
    colLoginId: "Login ID",
    colEmail: "Email",
    businessName: "Business Name",
    colSubscription: "Subscription",
    colRemaining: "Branch Count",
    colBranchCount: "Branch Count",
    addSubscriptionBtn: "Add subscription",
    addSubscriptionTitle: "Branch Subscriptions",
    addSubscriptionHint: "Select a branch to renew, extend by 1 month, or set inactive.",
    noBranchesForSubscription: "No branches found for this business.",
    saveBranchSubscriptionBtn: "Save Subscription",
    branchSubscriptionSaved: "Branch subscription updated.",
    branchBasedSubscription: "Branch-based",
    extendOneMonthBtn: "Extend +1 Month",
    activateBranchBtn: "Activate Branch",
    deactivateBranchBtn: "Deactivate Branch",
    branchExtendedOneMonth: "Branch subscription extended by 1 month.",
    branchActivatedMsg: "Branch activated.",
    branchDeactivatedMsg: "Branch deactivated.",
    editBusinessTitle: "Edit Business",
    colRegisteredAt: "Registration Date",
    colStatus: "Status",
    colAction: "Action",
    statusActive: "Active",
    statusInactive: "Inactive",
    editBtn: "Edit",
    deleteBtn: "Delete",
    editSubscriptionTitle: "Edit Business",
    selectFromListPrompt: "Click the Edit button of a business from the list.",
    loginIdField: "Login ID",
    loginIdPlaceholder: "e.g. AdaDoviz",
    businessEmailField: "Email",
    businessEmailPlaceholder: "example@company.com",
    loginIdEmailField: "Login ID",
    newPasswordOptionalField: "New Password (leave blank to keep unchanged)",
    subscriptionTypeLabel: "SUBSCRIPTION TYPE",
    customDaysLabel: "CUSTOM DAYS (+ADD / -SUBTRACT)",
    customDaysPlaceholder: "e.g. 15 or -10",
    currentRemainingLabel: "CURRENT REMAINING",
    afterUpdateLabel: "AFTER UPDATE",
    subscriptionPriceLabel: "AMOUNT",
    customPriceLabel: "CUSTOM PRICE (₺)",
    customPricePlaceholder: "e.g. 750",
    unlimitedSubscription: "Unlimited",
    resetSubscriptionBtn: "Reset Subscription",
    saveChangesBtn: "Save Changes",
    creatingBtn: "Creating...",
    createBusinessBtn: "Create Business",
    subTypeTest: "Test",
    subTypeMonthly: "Monthly",
    subTypeYearly: "Yearly",
    subTypeManual: "Manual",
    daysRemainingSuffix: "Left",
    minutesAgoSuffix: "min ago",
    hoursAgoSuffix: "hr ago",
    daysAgoSuffix: "days ago",
    justNow: "Just now",
    systemLogsTitle: "System Logs & Statistics",
    totalUniqueVisitors: "Total Unique Visitors",
    recentInteractions: "Recent User Interactions (Anonymous)",
    allBusinesses: "All Businesses",
    allCurrencies: "All Currencies",
    filterCurrencyLabel: "Currency",
    allActions: "All Actions",
    onlyLocationViewers: "Location Viewers Only",
    onlyCurrencyViewers: "Rate Viewers Only",
    onlyBusinessViewers: "Business Viewers Only",
    noAnonymousSessions: "No anonymous session records yet.",
    noMatchingRecords: "No records match the filters.",
    anonymousSession: "Anonymous session",
    estimatedLocation: "Estimated Location:",
    viewedBusinesses: "Businesses Viewed:",
    viewedRates: "Rates Viewed:",
    deleteBusinessTitle: "Delete Business",
    deleteConfirmTemplate:
      'Are you sure you want to permanently delete the business "{name}" and all of its data?',
    deleteWarning: "Warning: This action cannot be undone!",
    cancelAlt: "Cancel",
    confirmDeleteBtn: "Yes, Delete Permanently",
    resetSubConfirmText:
      "Are you sure you want to reset this business's subscription and set it to inactive? This action cannot be undone.",
    confirmResetBtn: "Yes, Reset",
    successTitle: "Success!",
    okBtn: "OK",
    changesAppliedMsg: "Changes applied successfully.",
    businessDeletedMsg: "Business permanently deleted.",
    subscriptionResetMsg: "Subscription reset; business set to inactive.",
    businessCreatedMsg: "New business created.",
    businessUpdatedMsg: "Business updated.",
    businessesLoadFailedMsg: "Failed to load businesses.",
    statusUpdateFailedMsg: "Failed to update status.",
    businessDeleteFailedMsg: "Failed to delete business.",
    creationFailedMsg: "Creation failed.",
    updateFailedMsg: "Update failed.",
    resetFailedMsg: "Reset failed.",
    expiredCantActivateMsg: "An expired business cannot be activated. Extend the subscription first.",
    selectFromListFirstMsg: "Select a business from the list first.",
    statsLoadFailedMsg: "Failed to load statistics.",
    activeToggleInactive: "Active — deactivate",
    inactiveToggleActive: "Inactive — activate",
    expiredToggleTitle: "Expired — extend the subscription first",
    logoUrlFieldNote: "",
    customerLabel: "Customer",
    businessWord: "Business",
    dateRangeLabel: "Date Range",
    dateFromLabel: "From",
    dateToLabel: "To",
    selectBusinessFilter: "Select Business",
    actionTypeLabel: "Action Type",
    actionTypeProfile: "Profile Update",
    actionTypeMargin: "Profit Margin Update",
    actionTypeBranch: "Branch Management",
    businessLogsSectionTitle: "Business Activity Logs",
    businessLogsEmpty: "No business logs match the filters.",
    loadingGeneric: "Loading...",
    chartNoData: "No data",
    chartNoPointsInRange: "No points to display in this range",
    rateLabel: "Rate",
    searchPlaceholder: "Search",
    noResults: "No results",
    selectCurrencyFirst: "Please select a currency first",
    selectExchangeOffice: "Select an exchange office",
    enterAmount: "Enter amount",
    selectCurrencyPrompt: "Select Currency",
    selectOfficePrompt: "Select Exchange Office",
    selectOfficeFirst: "Please select an exchange office first",
    enterAmountPrompt: "Enter the amount you want to convert",
    currencyOrBranchMissing: "Currency or branch not selected",
    businessChartInsufficientData: "Not enough data has been accumulated for this business yet.",
    businessChartWillBuild: "The chart will build automatically as rates are recorded.",
    branchesLabel: "Branches",
    chartTabLabel: "Chart",
    businessInfoTabLabel: "Business Info",
    addressLabelShort: "Address",
    phoneLabelShort: "Phone",
    whatsappLabelShort: "WhatsApp",
    workingHoursLabel: "Working Hours",
    workingHoursClosed: "Closed",
    workingHoursNotSet: "Not specified",
    weeklyHoursTitle: "Weekly Working Hours",
    viewWeeklySchedule: "View weekly schedule",
    getDirectionsBtn: "Get Directions",
    selectBranchForMap: "Select a branch to show on the map.",
    branchNoCoords: "No coordinates defined for this branch.",
    dayMon: "Monday",
    dayTue: "Tuesday",
    dayWed: "Wednesday",
    dayThu: "Thursday",
    dayFri: "Friday",
    daySat: "Saturday",
    daySun: "Sunday",
    branchesLoading: "Loading branches...",
    branchesEmpty: "No branches have been added for this business yet.",
    branchUsageLabel: "Branch Usage",
    addBranchBtn: "Add New Branch",
    branchLimitLabel: "Branch Limit",
    branchLimitTitle: "Branch Limit Reached",
    branchLimitContactMsg:
      "Please contact us to purchase or request an additional branch limit.",
    businessLedgerTitle: "Business Ledger",
    businessLedgerShort: "Business Ledger",
    subscriptionLedgerTitle: "Subscription Ledger",
    subscriptionLedgerShort: "Subscription Ledger",
    ledgerAmountLabel: "Amount",
    ledgerEmpty: "No records in this ledger yet.",
    navBestRate: "Best rate",
    bestRateTitle: "Today's best rate",
    bestRateLead:
      "Pick a currency and direction; enter an amount to see what each office would give you at its live rate. Offices are ranked from the best rate to the worst.",
    bestRateCurrency: "Currency",
    bestRateAmountBuy: "Foreign currency to exchange",
    bestRateAmountSell: "Amount in TRY",
    bestRateAmountHint: "Optional",
    bestRateResultBuy: "You receive (TRY)",
    bestRateResultSell: "You receive (FX)",
    bestRateBestBadge: "Best",
    bestRateEmpty: "No office is quoting this currency right now.",
    bestRateUpdated: "Last updated",
    navMap: "Map",
    mapTitle: "Exchange office map",
    mapLead:
      "See every exchange office in Northern Cyprus on the map: live USD/EUR/GBP rates, directions and WhatsApp. Allow location access to surface the closest ones.",
    mapOpenNow: "Open now",
    mapClosed: "Closed",
    mapNearMe: "Nearest to me",
    mapLocating: "Getting location…",
    mapLocateError: "Could not get your location. Check browser permissions.",
    mapLocateUnsupported: "Your browser does not support location services.",
    mapYouAreHere: "You are here",
    mapDirections: "Directions",
    mapDetail: "Details",
    mapAllCities: "All cities",
    mapEmpty: "No branch matches this filter.",
    mapBranchCount: "{n} branches",
    pwaInstallTitle: "Add AdaDöviz to your home screen",
    pwaInstallBody: "Live rates in one tap — opens like an app, no store needed.",
    pwaInstallAction: "Add",
    pwaInstallDismiss: "Not now",
  },
};

function getInitialLang() {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored === "tr" || stored === "en") return stored;
  } catch {
    /* ignore */
  }
  return "tr";
}

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(getInitialLang);

  /**
   * ⚠️ ERİŞİLEBİLİRLİK + TİPOGRAFİ DÜZELTMESİ (denetim bulguları A-04 / D-09):
   * index.html'de <html lang="tr"> sabit yazılı ve ilk render'da hiç
   * güncellenmiyordu. İki sonucu vardı:
   *   1) İngilizce sayfa ekran okuyucuya Türkçe olarak duyuruluyor, Google da
   *      Türkçe indeksliyordu.
   *   2) Tarayıcı Türkçe büyük harf kuralını uyguladığı için (i → İ) CSS
   *      `uppercase` ile yazılan İngilizce terimler bozuluyordu
   *      (ölçüm: "DUAL-WRİTE HATALARI", "SQLİTE ↔ SUPABASE FARKI").
   */
  useEffect(() => {
    document.documentElement.lang = lang;
  }, [lang]);

  const setLang = useCallback((next) => {
    const value = next === "en" ? "en" : "tr";
    setLangState(value);
    try {
      localStorage.setItem(STORAGE_KEY, value);
    } catch {
      /* ignore */
    }
    document.documentElement.lang = value;
  }, []);

  const toggleLang = useCallback(() => {
    setLangState((prev) => {
      const next = prev === "tr" ? "en" : "tr";
      try {
        localStorage.setItem(STORAGE_KEY, next);
      } catch {
        /* ignore */
      }
      document.documentElement.lang = next;
      return next;
    });
  }, []);

  const t = useCallback(
    (key) => {
      const dict = dictionaries[lang] || dictionaries.tr;
      return dict[key] ?? dictionaries.tr[key] ?? key;
    },
    [lang]
  );

  const value = useMemo(
    () => ({
      lang,
      setLang,
      toggleLang,
      t,
      dict: dictionaries[lang] || dictionaries.tr,
    }),
    [lang, setLang, toggleLang, t]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
