import { createContext, useCallback, useContext, useMemo, useState } from "react";

const LanguageContext = createContext(null);

const STORAGE_KEY = "finsight-lang";

// Not exported: named non-component exports break Vite Fast Refresh and can white-screen the app.
const dictionaries = {
  tr: {
    liveMarket: "Canlı Piyasa",
    businessLogin: "İşletme Girişi",
    businessPanel: "İşletme Paneli",
    adminPanel: "Admin Paneli",
    logout: "Çıkış Yap",
    partnership: "Partnerlik",
    marketSummary: "Piyasa Özeti",
    marketSummaryNote: "KKTC Merkez Bankası kurları baz alınarak yapılmıştır.",
    searchBanks: "Döviz bürosu ara...",
    openNow: "Şu An Açık",
    currencyConverter: "Döviz Çevirici",
    depositCalculator: "Mevduat Getiri Hesaplayıcı",
    loanCalculator: "Kredi Taksit Hesaplayıcı",
    currencyUnit: "Döviz Birimi",
    selectCurrency: "Döviz Seçiniz",
    operationType: "İşlem Türü",
    buy: "Alış",
    sell: "Satış",
    selectBank: "Döviz Bürosu Seç",
    selectBankPlaceholder: "Bir döviz bürosu seçin",
    amountTl: "Tutar (TL)",
    amountCurrency: "Tutar",
    resultBuy: "Alınacak",
    resultSell: "Elde Edilecek TL",
    resultWaiting: "Sonuç bekleniyor",
    sortLabel: "Sıralama",
    banksLoading: "Kur listesi yukleniyor veya baglanti hatası...",
    noBanksMatch: "Filtrelere uyan işletme bulunamadı.",
    themeLight: "Açık tema",
    themeDark: "Koyu tema",
    langTr: "TR",
    langEn: "EN",
    sortNearest: "En Yakın Konum",
    sortOpenNow: "Şu An Açık",
    sortNone: "Alfabetik",
    locationShareTitle: "Konum paylaşımı",
    locationShareConfirm:
      "En yakın konum sıralaması için konumunuz paylaşılacaktır. Onaylıyor musunuz?",
    locationShareAllow: "Konumu paylaş",
    locationShareDeny: "Vazgeç",
    locationPermissionRequired:
      "En yakın konum sıralaması için konum bilgilerine onay vermelisiniz.",
    locationUnsupported: "Tarayıcınız konum servisini desteklemiyor.",
    notificationsTitle: "Bildirimler",
    notificationsEmpty: "Henüz bildiriminiz yok.",
    notificationsMarkAllRead: "Tümünü okundu işaretle",
    notifBranchApprovedTitle: "Şube talebi onaylandı",
    notifBranchRejectedTitle: "Şube talebi reddedildi",
    sortGbpBuyHigh: "En Yüksek Alış (GBP)",
    sortGbpBuyLow: "En Düşük Alış (GBP)",
    sortUsdBuyHigh: "En Yüksek Alış (USD)",
    sortUsdBuyLow: "En Düşük Alış (USD)",
    sortEurBuyHigh: "En Yüksek Alış (EUR)",
    sortEurBuyLow: "En Düşük Alış (EUR)",
    periodHourly: "Saatlik",
    periodDaily: "Günlük",
    periodWeekly: "Haftalık",
    periodMonthly: "Aylık",
    periodYearly: "Yıllık",
    backToDashboard: "Dashboard",
    managementPanel: "Yönetim Paneli",
    lastUpdate: "Son Güncelleme",
    subscriptionStatus: "Abonelik Durumu",
    remainingSubscription: "Kalan Abonelik Süresi",
    subscriptionExpired: "Süresi Bitti",
    daysUnit: "Gün",
    centralBankRates: "Merkez Bankası Kurları (Salt Okunur)",
    centralBankRatesNote: "Aşağıdaki kurlar KKTC Merkez Bankası XML kaynağından gelmektedir.",
    subscriptionExpiredNotice:
      "Abonelik süreniz dolmuştur. Kâr marjı ayarları yalnızca görüntülenebilir; güncelleme yapılamaz.",
    buyRates: "ALIŞ KURLAR",
    sellRates: "SATIŞ KURLAR",
    centralBankRate: "Merkez Bankası KUR",
    effectiveRate: "Efektif",
    profitType: "Kâr Tipi",
    profitMargin: "Kâr Marjı",
    profitValue: "Kâr Değeri",
    fixedPrice: "Baz Fiyat (TL)",
    percentPrice: "Yüzdesel (%)",
    finalRate: "Final Kur",
    profitTl: "TL Kâr",
    saveMargins: "Kâr Marjlarını Kaydet",
    saving: "Kaydediliyor...",
    logoutShort: "Çıkış",
    changePassword: "Şifre Değiştir",
    changePasswordTitle: "Şifre Değiştir",
    oldPassword: "Eski Şifre",
    newPassword: "Yeni Şifre",
    confirmPassword: "Yeni Şifre (Tekrar)",
    confirmPasswordAction: "Onayla",
    cancel: "Vazgeç",
    selectBranchPlaceholder: "Şube seçiniz",
    branchPhoneLabel: "Şube Numarası",
    whatsappPhoneLabel: "WhatsApp iletişim numarası",
    selectBranchToEditPhones: "Düzenlemek için önce bir şube seçin.",
    saveBranchPhonesBtn: "Telefonları Kaydet",
    branchNameLabel: "Şube Adı",
    branchNamePlaceholder: "Şube adını girin",
    updateBranchNameHint: "Şube adını güncelle",
    subscriptionStartDate: "Başlangıç tarihi",
    subscriptionListEmpty: "Henüz şube kaydı yok.",
    subscriptionExpiringSoon: "Abonelik Süresi bitiyor",
    saveBranchNameBtn: "Kaydet",
    loadingShort: "Yükleniyor...",
    newBranchRequestBtn: "Yeni şube Talebi",
    newBranchRequestTitle: "Yeni Şube Talebi",
    newBranchRequestConfirm:
      "Girdiğiniz bilgilerle yeni bir şube talebi oluşturulacak. Kabul ediyor musunuz?",
    newBranchRequestSuccess: "Şube talebiniz iletildi.",
    confirmRequestBtn: "Evet, Talep Oluştur",
    addBranchDirectBtn: "Şube Ekle",
    addBranchDirectTitle: "Yeni Şube Ekle",
    addBranchDirectConfirm:
      "Şube bilgileriniz Super Admin’e onay için iletilecek. Onaylanana kadar şube aktif olmaz. Kabul ediyor musunuz?",
    addBranchDirectSuccess: "Şube talebiniz iletildi. Admin onayı bekleniyor.",
    addBranchAwaitingAdminSuccess: "Şube talebiniz iletildi. Admin onayı bekleniyor.",
    confirmAddBranchBtn: "Evet, Onaya Gönder",
    renewBranchRequestBtn: "Yenileme Talebi",
    renewBranchRequestSuccess: "Şube yenileme talebiniz iletildi.",
    renewBranchRequestPending: "Yenileme talebi bekliyor",
    renewBranchRequestConfirm:
      "Bu pasif şube için yöneticiye yenileme talebi gönderilecek. Onaylıyor musunuz?",
    requestTypeNew: "Yeni şube",
    requestTypeRenew: "Yenileme",
    branchInactiveLabel: "Pasif",
    tabRequests: "Talepler",
    requestsEmpty: "Henüz şube talebi yok.",
    requestStatusPending: "Bekliyor",
    requestStatusApproved: "Onaylandı",
    requestStatusRejected: "Reddedildi",
    approveRequestBtn: "Onayla",
    rejectRequestBtn: "Reddet",
    requestBusinessLabel: "İşletme",
    requestCreatedAt: "Talep tarihi",
    branchLocationTitle: "Şube Konumu",
    branchAddressLabel: "Adres",
    branchAddressPlaceholder: "Haritaya tıklayın veya adresi yazın",
    branchMapHint: "Konum seçmek için haritaya tıklayın",
    saveBranchLocationBtn: "Konumu Kaydet",
    saveWorkingHoursBtn: "Saatleri Kaydet",
    passwordMismatch: "Yeni şifreler eşleşmiyor.",
    passwordChangedSuccess: "Şifre başarıyla değiştirildi.",
    footerTagline: "Kuzey Kıbrıs'ın Döviz Adresi",
    partnershipDesc: "AdaDöviz ile iş ortaklığı kurmak için başvuru formunu doldurun. Biz size ulaşalım.",
    institutionName: "Kurum Adı",
    contactPerson: "Yetkili Kişi",
    emailLabel: "E-posta",
    phoneLabel: "Telefon",
    messageLabel: "Mesaj",
    institutionNamePlaceholder: "Örn: Ada Döviz",
    contactPersonPlaceholder: "Örn: Tuna Gül",
    emailPlaceholder: "partner@kurum.com",
    phonePlaceholder: "+90 5XX XXX XX XX",
    messagePlaceholder: "Sözleşme kapsamı ve talebinizi kısaca belirtin...",
    messageTemplatePreviewLabel: "Boş bırakılırsa gönderilecek mesaj",
    phoneIncompleteError: "Lütfen 10 haneli telefon numarasını eksiksiz girin.",
    submitApplication: "Başvuruyu Gönder",
    submitting: "Gönderiliyor...",
    applicationSuccess: "Başvurunuz başarıyla gönderildi. En kısa sürede size dönüş yapacağız.",
    applicationSendFailed: "Gönderme başarısız.",
    businessLoginSubtitle: "Kurum hesabınızla oranlarınızı yönetin",
    usernameLabel: "Giriş ID",
    usernamePlaceholder: "örn: AdaDoviz",
    passwordLabel: "Şifre",
    forgotPassword: "Şifremi Unuttum",
    rememberMe: "Oturumu açık tut",
    loginButton: "Giriş Yap",
    loggingIn: "Giriş yapılıyor...",
    loggingInTitle: "Giriş Yapılıyor...",
    loggingInSubtitle: "Yönlendiriliyorsunuz",
    loginFailed: "Giriş başarısız.",
    forgotPasswordTitle: "Şifremi Unuttum",
    forgotPasswordDesc:
      "Kayıtlı e-posta veya Giriş ID’nizi girin. Sıfırlama bağlantısı yalnızca kayıtlı e-posta adresinize gönderilir.",
    emailOrUsername: "E-posta veya Giriş ID",
    emailOrUsernamePlaceholder: "ornek@firma.com veya giris-id",
    send: "Gönder",
    sending: "Gönderiliyor...",
    forgotRequestFailed: "İstek gönderilemedi.",
    forgotSuccessDefault: "Eğer bu hesap sistemde kayıtlıysa, şifre sıfırlama bağlantısı e-posta adresinize gönderildi.",
    superAdminTitle: "Super Admin Paneli",
    superAdminSubtitle: "İşletme ve abonelik yönetimi",
    backToDashboardLink: "Dashboard'a Dön",
    logsButton: "Loglar",
    seoButton: "SEO",
    seoModalTitle: "SEO Optimizasyonu",
    seoModalHint:
      "Google’da 1. sıra garanti edilemez. Bu ayarlar arama motorlarının sitenizi doğru anlamasına yardımcı olur (başlık, açıklama, anahtar kelimeler, sitemap).",
    seoSiteName: "Site adı",
    seoTitle: "Sayfa başlığı (title)",
    seoDescription: "Meta açıklama",
    seoKeywords: "Anahtar kelimeler",
    seoCanonical: "Canonical URL",
    seoOgImage: "Sosyal görsel URL (og:image)",
    seoRobots: "Robots",
    seoGeoRegion: "Coğrafi bölge",
    seoGeoPlace: "Konum adı",
    seoFocusQueries: "Hedef arama ifadeleri",
    seoStructuredData: "Yapılandırılmış veri (JSON-LD) açık",
    seoSaveBtn: "SEO Ayarlarını Kaydet",
    seoSavedMsg: "SEO ayarları kaydedildi.",
    seoLoadFailed: "SEO ayarları yüklenemedi.",
    seoSaveFailed: "SEO ayarları kaydedilemedi.",
    tabList: "Mevcut İşletmeler",
    tabEdit: "İşletme Düzenle & Abonelik",
    tabCreate: "Yeni İşletme Ekle",
    refresh: "Yenile",
    loadingList: "Liste yükleniyor...",
    noBusinessesYet: "Henüz işletme yok.",
    colId: "ID",
    colLoginId: "Giriş ID",
    colEmail: "E-posta",
    businessName: "İşletme Adı",
    colSubscription: "Abonelik",
    colRemaining: "Şube Sayısı",
    colBranchCount: "Şube Sayısı",
    addSubscriptionBtn: "Abonelik ekle",
    addSubscriptionTitle: "Şube Abonelikleri",
    addSubscriptionHint: "Şube seçip aboneliğini yenileyin, 1 ay uzatın veya pasife alın.",
    noBranchesForSubscription: "Bu işletmeye ait şube bulunamadı.",
    saveBranchSubscriptionBtn: "Abonelik Kaydet",
    branchSubscriptionSaved: "Şube aboneliği güncellendi.",
    branchBasedSubscription: "Şube bazlı",
    extendOneMonthBtn: "+1 Ay Uzat",
    activateBranchBtn: "Şubeyi Aktifleştir",
    deactivateBranchBtn: "Şubeyi Pasife Al",
    branchExtendedOneMonth: "Şube aboneliği 1 ay uzatıldı.",
    branchActivatedMsg: "Şube aktifleştirildi.",
    branchDeactivatedMsg: "Şube pasife alındı.",
    editBusinessTitle: "İşletmeyi Düzenle",
    colRegisteredAt: "Kayıt Tarihi",
    colStatus: "Durum",
    colAction: "İşlem",
    statusActive: "Aktif",
    statusInactive: "Pasif",
    editBtn: "Düzenle",
    deleteBtn: "Sil",
    editSubscriptionTitle: "İşletmeyi Düzenle",
    selectFromListPrompt: "Listeden bir işletmenin Düzenle butonuna tıklayın.",
    loginIdField: "Giriş ID",
    loginIdPlaceholder: "örn: AdaDoviz",
    businessEmailField: "E-posta",
    businessEmailPlaceholder: "ornek@firma.com",
    loginIdEmailField: "Giriş ID",
    newPasswordOptionalField: "Yeni Şifre (boş bırakırsanız değişmez)",
    subscriptionTypeLabel: "ABONELİK TİPİ",
    customDaysLabel: "ÖZEL GÜN (+EKLE / -ÇIKAR)",
    customDaysPlaceholder: "Örn: 15 veya -10",
    currentRemainingLabel: "MEVCUT KALAN",
    afterUpdateLabel: "GÜNCELLEME SONRASI",
    subscriptionPriceLabel: "TUTAR",
    customPriceLabel: "ÖZEL TUTAR (₺)",
    customPricePlaceholder: "Örn: 750",
    unlimitedSubscription: "Sınırsız",
    resetSubscriptionBtn: "Aboneliği Sıfırla",
    saveChangesBtn: "Değişiklikleri Kaydet",
    creatingBtn: "Oluşturuluyor...",
    createBusinessBtn: "İşletmeyi Oluştur",
    subTypeTest: "Test",
    subTypeMonthly: "Aylık",
    subTypeYearly: "Yıllık",
    subTypeManual: "Manuel",
    daysRemainingSuffix: "Kaldı",
    minutesAgoSuffix: "dk önce",
    hoursAgoSuffix: "sa önce",
    daysAgoSuffix: "gün önce",
    justNow: "Az önce",
    systemLogsTitle: "Sistem Logları ve İstatistikler",
    totalUniqueVisitors: "Toplam Tekil Ziyaretçi Sayısı",
    recentInteractions: "Son Kullanıcı Etkileşimleri (Anonim)",
    allBusinesses: "Tüm İşletmeler",
    allCurrencies: "Tüm Dövizler",
    allActions: "Tüm Aksiyonlar",
    onlyLocationViewers: "Sadece Konum İnceleyenler",
    onlyCurrencyViewers: "Sadece Kur İnceleyenler",
    onlyBusinessViewers: "Sadece İşletme İnceleyenler",
    noAnonymousSessions: "Henüz anonim oturum kaydı yok.",
    noMatchingRecords: "Filtrelere uyan kayıt bulunamadı.",
    anonymousSession: "Anonim oturum",
    estimatedLocation: "Tahmini Konum:",
    viewedBusinesses: "İncelenen İşletmeler:",
    viewedRates: "Bakılan Kurlar:",
    deleteBusinessTitle: "İşletmeyi Sil",
    deleteConfirmTemplate:
      '"{name}" adlı işletmeyi ve bu işletmeye ait tüm verileri kalıcı olarak silmek istediğinize emin misiniz?',
    deleteWarning: "Dikkat: Bu işlem geri alınamaz!",
    cancelAlt: "İptal",
    confirmDeleteBtn: "Evet, Kalıcı Olarak Sil",
    resetSubConfirmText:
      "Bu işletmenin aboneliğini sıfırlayıp pasif duruma çekmek istediğinize emin misiniz? Bu işlem geri alınamaz.",
    confirmResetBtn: "Evet, Sıfırla",
    successTitle: "Başarılı!",
    okBtn: "Tamam",
    changesAppliedMsg: "Değişiklikler başarıyla uygulandı.",
    businessDeletedMsg: "İşletme kalıcı olarak silindi.",
    subscriptionResetMsg: "Abonelik sıfırlandı; işletme pasife alındı.",
    businessCreatedMsg: "Yeni işletme oluşturuldu.",
    businessUpdatedMsg: "İşletme güncellendi.",
    businessesLoadFailedMsg: "İşletmeler yüklenemedi.",
    statusUpdateFailedMsg: "Durum güncellenemedi.",
    businessDeleteFailedMsg: "İşletme silinemedi.",
    creationFailedMsg: "Oluşturma başarısız.",
    updateFailedMsg: "Güncelleme başarısız.",
    resetFailedMsg: "Sıfırlama başarısız.",
    expiredCantActivateMsg: "Süresi bitmiş işletme aktif edilemez. Önce abonelik süresini uzatın.",
    selectFromListFirstMsg: "Önce listeden bir işletme seçin.",
    statsLoadFailedMsg: "İstatistikler alınamadı.",
    activeToggleInactive: "Aktif — pasife al",
    inactiveToggleActive: "Pasif — aktife al",
    expiredToggleTitle: "Süresi bitmiş — önce abonelik süresini uzatın",
    logoUrlFieldNote: "",
    customerLabel: "Müşteri",
    businessWord: "İşletme",
    dateRangeLabel: "Tarih Aralığı",
    dateFromLabel: "Başlangıç",
    dateToLabel: "Bitiş",
    selectBusinessFilter: "İşletme Seçimi",
    actionTypeLabel: "İşlem Tipi",
    actionTypeProfile: "Profil Güncelleme",
    actionTypeMargin: "Kâr Marjı Güncelleme",
    actionTypeBranch: "Şube Yönetimi",
    businessLogsSectionTitle: "İşletme İşlem Kayıtları",
    businessLogsEmpty: "Filtrelere uyan işletme logu bulunamadı.",
    loadingGeneric: "Yükleniyor...",
    selectCurrencyFirst: "Lütfen önce Döviz Birimi seçin",
    selectExchangeOffice: "Bir döviz bürosu seçin",
    enterAmount: "Tutar giriniz",
    selectCurrencyPrompt: "Döviz Seçiniz",
    selectOfficePrompt: "Döviz Bürosu Seçin",
    enterAmountPrompt: "Dönüştürmek istediğiniz tutarı giriniz",
    currencyOrBranchMissing: "Döviz birimi ya da şube seçilmedi",
    businessChartInsufficientData: "Bu işletme için henüz yeterli veri birikmemiş.",
    businessChartWillBuild: "Kurlar kaydedildikçe grafik otomatik olarak oluşacaktır.",
    branchesLabel: "Şubeler",
    chartTabLabel: "Grafik",
    businessInfoTabLabel: "İşletme Bilgileri",
    addressLabelShort: "Adres",
    phoneLabelShort: "Telefon",
    whatsappLabelShort: "WhatsApp",
    workingHoursLabel: "Çalışma Saatleri",
    workingHoursClosed: "Kapalı",
    workingHoursNotSet: "Belirtilmemiş",
    weeklyHoursTitle: "Haftalık Çalışma Saatleri",
    viewWeeklySchedule: "Haftalık programı gör",
    getDirectionsBtn: "Yol Tarifi Al",
    selectBranchForMap: "Haritada göstermek için bir şube seçin.",
    branchNoCoords: "Bu şube için konum koordinatı tanımlı değil.",
    dayMon: "Pazartesi",
    dayTue: "Salı",
    dayWed: "Çarşamba",
    dayThu: "Perşembe",
    dayFri: "Cuma",
    daySat: "Cumartesi",
    daySun: "Pazar",
    branchesLoading: "Şubeler yükleniyor...",
    branchesEmpty: "Bu işletmeye henüz şube eklenmemiş.",
    branchUsageLabel: "Şube Kullanımı",
    addBranchBtn: "Yeni Şube Ekle",
    branchLimitLabel: "Şube Limiti",
    branchLimitTitle: "Şube Limitine Ulaşıldı",
    branchLimitContactMsg:
      "Yeni şube limiti satın almak / talep etmek için iletişime geçin.",
    businessLedgerTitle: "İşletme Dökümü",
    businessLedgerShort: "İşletme Dökümü",
    subscriptionLedgerTitle: "Abonelik Dökümü",
    subscriptionLedgerShort: "Abonelik Dökümü",
    ledgerAmountLabel: "Tutar",
    ledgerEmpty: "Bu dökümde henüz kayıt yok.",
    chartNoData: "Veri yok",
    chartNoPointsInRange: "Bu aralıkta gösterilecek nokta yok",
    rateLabel: "Kur",
    searchPlaceholder: "Ara...",
    noResults: "Sonuç yok",
  },
  en: {
    liveMarket: "Live Market",
    businessLogin: "Business Login",
    businessPanel: "Business Panel",
    adminPanel: "Admin Panel",
    logout: "Log Out",
    partnership: "Partnership",
    marketSummary: "Market Summary",
    marketSummaryNote: "Based on Central Bank of Northern Cyprus rates.",
    searchBanks: "Search exchange offices...",
    openNow: "Open Now",
    currencyConverter: "Currency Converter",
    depositCalculator: "Deposit Return Calculator",
    loanCalculator: "Loan Installment Calculator",
    currencyUnit: "Currency",
    selectCurrency: "Select Currency",
    operationType: "Operation",
    buy: "Buy",
    sell: "Sell",
    selectBank: "Select Exchange Office",
    selectBankPlaceholder: "Select an exchange office",
    amountTl: "Amount (TRY)",
    amountCurrency: "Amount",
    resultBuy: "You get",
    resultSell: "You get TRY",
    resultWaiting: "Waiting for result",
    sortLabel: "Sort",
    banksLoading: "Loading rates or connection error...",
    noBanksMatch: "No businesses match the filters.",
    themeLight: "Light theme",
    themeDark: "Dark theme",
    langTr: "TR",
    langEn: "EN",
    sortNearest: "Nearest Location",
    sortOpenNow: "Open Now",
    sortNone: "Alphabetical",
    locationShareTitle: "Share location",
    locationShareConfirm:
      "Your location will be shared to sort by nearest location. Do you approve?",
    locationShareAllow: "Share location",
    locationShareDeny: "Cancel",
    locationPermissionRequired:
      "You must allow location access to sort by nearest location.",
    locationUnsupported: "Your browser does not support location services.",
    notificationsTitle: "Notifications",
    notificationsEmpty: "You have no notifications yet.",
    notificationsMarkAllRead: "Mark all as read",
    notifBranchApprovedTitle: "Branch request approved",
    notifBranchRejectedTitle: "Branch request rejected",
    sortGbpBuyHigh: "Highest Buy (GBP)",
    sortGbpBuyLow: "Lowest Buy (GBP)",
    sortUsdBuyHigh: "Highest Buy (USD)",
    sortUsdBuyLow: "Lowest Buy (USD)",
    sortEurBuyHigh: "Highest Buy (EUR)",
    sortEurBuyLow: "Lowest Buy (EUR)",
    periodHourly: "Hourly",
    periodDaily: "Daily",
    periodWeekly: "Weekly",
    periodMonthly: "Monthly",
    periodYearly: "Yearly",
    backToDashboard: "Dashboard",
    managementPanel: "Management Panel",
    lastUpdate: "Last Update",
    subscriptionStatus: "Subscription Status",
    remainingSubscription: "Remaining Subscription",
    subscriptionExpired: "Expired",
    daysUnit: "Days",
    centralBankRates: "Central Bank Rates (Read-only)",
    centralBankRatesNote: "The rates below are sourced from the TRNC Central Bank XML feed.",
    subscriptionExpiredNotice:
      "Your subscription has expired. Margin settings are view-only and cannot be updated.",
    buyRates: "BUY RATES",
    sellRates: "SELL RATES",
    centralBankRate: "Central Bank Rate",
    effectiveRate: "Effective",
    profitType: "Profit Type",
    profitMargin: "Profit Margin",
    profitValue: "Profit Value",
    fixedPrice: "Fixed (TRY)",
    percentPrice: "Percent (%)",
    finalRate: "Final Rate",
    profitTl: "TRY Profit",
    saveMargins: "Save Profit Margins",
    saving: "Saving...",
    logoutShort: "Log Out",
    changePassword: "Change Password",
    changePasswordTitle: "Change Password",
    oldPassword: "Current Password",
    newPassword: "New Password",
    confirmPassword: "Confirm New Password",
    confirmPasswordAction: "Confirm",
    cancel: "Cancel",
    selectBranchPlaceholder: "Select branch",
    branchPhoneLabel: "Branch Number",
    whatsappPhoneLabel: "WhatsApp contact number",
    selectBranchToEditPhones: "Select a branch first to edit.",
    saveBranchPhonesBtn: "Save Phones",
    branchNameLabel: "Branch Name",
    branchNamePlaceholder: "Enter branch name",
    updateBranchNameHint: "Update branch name",
    subscriptionStartDate: "Start date",
    subscriptionListEmpty: "No branches yet.",
    subscriptionExpiringSoon: "Subscription expiring",
    saveBranchNameBtn: "Save",
    loadingShort: "Loading...",
    newBranchRequestBtn: "New branch request",
    newBranchRequestTitle: "New Branch Request",
    newBranchRequestConfirm:
      "A new branch request will be created with the details you entered. Do you accept?",
    newBranchRequestSuccess: "Your branch request has been submitted.",
    confirmRequestBtn: "Yes, Create Request",
    addBranchDirectBtn: "Add Branch",
    addBranchDirectTitle: "Add New Branch",
    addBranchDirectConfirm:
      "Your branch details will be sent to Super Admin for approval. The branch stays inactive until approved. Do you accept?",
    addBranchDirectSuccess: "Branch request submitted. Waiting for admin approval.",
    addBranchAwaitingAdminSuccess: "Branch request submitted. Waiting for admin approval.",
    confirmAddBranchBtn: "Yes, Send for Approval",
    renewBranchRequestBtn: "Renewal Request",
    renewBranchRequestSuccess: "Your branch renewal request has been submitted.",
    renewBranchRequestPending: "Renewal request pending",
    renewBranchRequestConfirm:
      "A renewal request for this inactive branch will be sent to the admin. Do you confirm?",
    requestTypeNew: "New branch",
    requestTypeRenew: "Renewal",
    branchInactiveLabel: "Inactive",
    tabRequests: "Requests",
    requestsEmpty: "No branch requests yet.",
    requestStatusPending: "Pending",
    requestStatusApproved: "Approved",
    requestStatusRejected: "Rejected",
    approveRequestBtn: "Approve",
    rejectRequestBtn: "Reject",
    requestBusinessLabel: "Business",
    requestCreatedAt: "Request date",
    branchLocationTitle: "Branch Location",
    branchAddressLabel: "Address",
    branchAddressPlaceholder: "Click the map or type an address",
    branchMapHint: "Click the map to pick a location",
    saveBranchLocationBtn: "Save Location",
    saveWorkingHoursBtn: "Save Hours",
    passwordMismatch: "New passwords do not match.",
    passwordChangedSuccess: "Password changed successfully.",
    footerTagline: "Northern Cyprus's Currency Address",
    partnershipDesc: "Fill out the application form to become a partner with AdaDöviz. We'll get in touch with you.",
    institutionName: "Institution Name",
    contactPerson: "Contact Person",
    emailLabel: "Email",
    phoneLabel: "Phone",
    messageLabel: "Message",
    institutionNamePlaceholder: "e.g. Ada Döviz",
    contactPersonPlaceholder: "e.g. Tuna Gül",
    emailPlaceholder: "partner@company.com",
    phonePlaceholder: "+90 5XX XXX XX XX",
    messagePlaceholder: "Briefly describe your request and scope of partnership...",
    messageTemplatePreviewLabel: "Message that will be sent if left empty",
    phoneIncompleteError: "Please enter the full 10-digit phone number.",
    submitApplication: "Submit Application",
    submitting: "Submitting...",
    applicationSuccess: "Your application has been submitted successfully. We'll get back to you shortly.",
    applicationSendFailed: "Submission failed.",
    businessLoginSubtitle: "Manage your rates with your business account",
    usernameLabel: "Login ID",
    usernamePlaceholder: "e.g. AdaDoviz",
    passwordLabel: "Password",
    forgotPassword: "Forgot Password",
    rememberMe: "Keep me signed in",
    loginButton: "Log In",
    loggingIn: "Logging in...",
    loggingInTitle: "Logging In...",
    loggingInSubtitle: "You are being redirected",
    loginFailed: "Login failed.",
    forgotPasswordTitle: "Forgot Password",
    forgotPasswordDesc:
      "Enter your registered email or Login ID. The reset link is sent only to the stored email address.",
    emailOrUsername: "Email or Login ID",
    emailOrUsernamePlaceholder: "example@company.com or login-id",
    send: "Send",
    sending: "Sending...",
    forgotRequestFailed: "Request failed.",
    forgotSuccessDefault: "If this account is registered in the system, a password reset link has been sent to your email.",
    superAdminTitle: "Super Admin Panel",
    superAdminSubtitle: "Business & subscription management",
    backToDashboardLink: "Back to Dashboard",
    logsButton: "Logs",
    seoButton: "SEO",
    seoModalTitle: "SEO Optimization",
    seoModalHint:
      "A #1 Google ranking cannot be guaranteed. These settings help search engines understand your site (title, description, keywords, sitemap).",
    seoSiteName: "Site name",
    seoTitle: "Page title",
    seoDescription: "Meta description",
    seoKeywords: "Keywords",
    seoCanonical: "Canonical URL",
    seoOgImage: "Social image URL (og:image)",
    seoRobots: "Robots",
    seoGeoRegion: "Geo region",
    seoGeoPlace: "Place name",
    seoFocusQueries: "Target search queries",
    seoStructuredData: "Structured data (JSON-LD) enabled",
    seoSaveBtn: "Save SEO Settings",
    seoSavedMsg: "SEO settings saved.",
    seoLoadFailed: "Failed to load SEO settings.",
    seoSaveFailed: "Failed to save SEO settings.",
    tabList: "Current Businesses",
    tabEdit: "Edit Business & Subscription",
    tabCreate: "Add New Business",
    refresh: "Refresh",
    loadingList: "Loading list...",
    noBusinessesYet: "No businesses yet.",
    colId: "ID",
    colLoginId: "Login ID",
    colEmail: "Email",
    businessName: "Business Name",
    colSubscription: "Subscription",
    colRemaining: "Branch Count",
    colBranchCount: "Branch Count",
    addSubscriptionBtn: "Add subscription",
    addSubscriptionTitle: "Branch Subscriptions",
    addSubscriptionHint: "Select a branch to renew, extend by 1 month, or set inactive.",
    noBranchesForSubscription: "No branches found for this business.",
    saveBranchSubscriptionBtn: "Save Subscription",
    branchSubscriptionSaved: "Branch subscription updated.",
    branchBasedSubscription: "Branch-based",
    extendOneMonthBtn: "Extend +1 Month",
    activateBranchBtn: "Activate Branch",
    deactivateBranchBtn: "Deactivate Branch",
    branchExtendedOneMonth: "Branch subscription extended by 1 month.",
    branchActivatedMsg: "Branch activated.",
    branchDeactivatedMsg: "Branch deactivated.",
    editBusinessTitle: "Edit Business",
    colRegisteredAt: "Registration Date",
    colStatus: "Status",
    colAction: "Action",
    statusActive: "Active",
    statusInactive: "Inactive",
    editBtn: "Edit",
    deleteBtn: "Delete",
    editSubscriptionTitle: "Edit Business",
    selectFromListPrompt: "Click the Edit button of a business from the list.",
    loginIdField: "Login ID",
    loginIdPlaceholder: "e.g. AdaDoviz",
    businessEmailField: "Email",
    businessEmailPlaceholder: "example@company.com",
    loginIdEmailField: "Login ID",
    newPasswordOptionalField: "New Password (leave blank to keep unchanged)",
    subscriptionTypeLabel: "SUBSCRIPTION TYPE",
    customDaysLabel: "CUSTOM DAYS (+ADD / -SUBTRACT)",
    customDaysPlaceholder: "e.g. 15 or -10",
    currentRemainingLabel: "CURRENT REMAINING",
    afterUpdateLabel: "AFTER UPDATE",
    subscriptionPriceLabel: "AMOUNT",
    customPriceLabel: "CUSTOM PRICE (₺)",
    customPricePlaceholder: "e.g. 750",
    unlimitedSubscription: "Unlimited",
    resetSubscriptionBtn: "Reset Subscription",
    saveChangesBtn: "Save Changes",
    creatingBtn: "Creating...",
    createBusinessBtn: "Create Business",
    subTypeTest: "Test",
    subTypeMonthly: "Monthly",
    subTypeYearly: "Yearly",
    subTypeManual: "Manual",
    daysRemainingSuffix: "Left",
    minutesAgoSuffix: "min ago",
    hoursAgoSuffix: "hr ago",
    daysAgoSuffix: "days ago",
    justNow: "Just now",
    systemLogsTitle: "System Logs & Statistics",
    totalUniqueVisitors: "Total Unique Visitors",
    recentInteractions: "Recent User Interactions (Anonymous)",
    allBusinesses: "All Businesses",
    allCurrencies: "All Currencies",
    allActions: "All Actions",
    onlyLocationViewers: "Location Viewers Only",
    onlyCurrencyViewers: "Rate Viewers Only",
    onlyBusinessViewers: "Business Viewers Only",
    noAnonymousSessions: "No anonymous session records yet.",
    noMatchingRecords: "No records match the filters.",
    anonymousSession: "Anonymous session",
    estimatedLocation: "Estimated Location:",
    viewedBusinesses: "Businesses Viewed:",
    viewedRates: "Rates Viewed:",
    deleteBusinessTitle: "Delete Business",
    deleteConfirmTemplate:
      'Are you sure you want to permanently delete the business "{name}" and all of its data?',
    deleteWarning: "Warning: This action cannot be undone!",
    cancelAlt: "Cancel",
    confirmDeleteBtn: "Yes, Delete Permanently",
    resetSubConfirmText:
      "Are you sure you want to reset this business's subscription and set it to inactive? This action cannot be undone.",
    confirmResetBtn: "Yes, Reset",
    successTitle: "Success!",
    okBtn: "OK",
    changesAppliedMsg: "Changes applied successfully.",
    businessDeletedMsg: "Business permanently deleted.",
    subscriptionResetMsg: "Subscription reset; business set to inactive.",
    businessCreatedMsg: "New business created.",
    businessUpdatedMsg: "Business updated.",
    businessesLoadFailedMsg: "Failed to load businesses.",
    statusUpdateFailedMsg: "Failed to update status.",
    businessDeleteFailedMsg: "Failed to delete business.",
    creationFailedMsg: "Creation failed.",
    updateFailedMsg: "Update failed.",
    resetFailedMsg: "Reset failed.",
    expiredCantActivateMsg: "An expired business cannot be activated. Extend the subscription first.",
    selectFromListFirstMsg: "Select a business from the list first.",
    statsLoadFailedMsg: "Failed to load statistics.",
    activeToggleInactive: "Active — deactivate",
    inactiveToggleActive: "Inactive — activate",
    expiredToggleTitle: "Expired — extend the subscription first",
    logoUrlFieldNote: "",
    customerLabel: "Customer",
    businessWord: "Business",
    dateRangeLabel: "Date Range",
    dateFromLabel: "From",
    dateToLabel: "To",
    selectBusinessFilter: "Select Business",
    actionTypeLabel: "Action Type",
    actionTypeProfile: "Profile Update",
    actionTypeMargin: "Profit Margin Update",
    actionTypeBranch: "Branch Management",
    businessLogsSectionTitle: "Business Activity Logs",
    businessLogsEmpty: "No business logs match the filters.",
    loadingGeneric: "Loading...",
    chartNoData: "No data",
    chartNoPointsInRange: "No points to display in this range",
    rateLabel: "Rate",
    searchPlaceholder: "Search...",
    noResults: "No results",
    selectCurrencyFirst: "Please select a currency first",
    selectExchangeOffice: "Select an exchange office",
    enterAmount: "Enter amount",
    selectCurrencyPrompt: "Select Currency",
    selectOfficePrompt: "Select Exchange Office",
    enterAmountPrompt: "Enter the amount you want to convert",
    currencyOrBranchMissing: "Currency or branch not selected",
    businessChartInsufficientData: "Not enough data has been accumulated for this business yet.",
    businessChartWillBuild: "The chart will build automatically as rates are recorded.",
    branchesLabel: "Branches",
    chartTabLabel: "Chart",
    businessInfoTabLabel: "Business Info",
    addressLabelShort: "Address",
    phoneLabelShort: "Phone",
    whatsappLabelShort: "WhatsApp",
    workingHoursLabel: "Working Hours",
    workingHoursClosed: "Closed",
    workingHoursNotSet: "Not specified",
    weeklyHoursTitle: "Weekly Working Hours",
    viewWeeklySchedule: "View weekly schedule",
    getDirectionsBtn: "Get Directions",
    selectBranchForMap: "Select a branch to show on the map.",
    branchNoCoords: "No coordinates defined for this branch.",
    dayMon: "Monday",
    dayTue: "Tuesday",
    dayWed: "Wednesday",
    dayThu: "Thursday",
    dayFri: "Friday",
    daySat: "Saturday",
    daySun: "Sunday",
    branchesLoading: "Loading branches...",
    branchesEmpty: "No branches have been added for this business yet.",
    branchUsageLabel: "Branch Usage",
    addBranchBtn: "Add New Branch",
    branchLimitLabel: "Branch Limit",
    branchLimitTitle: "Branch Limit Reached",
    branchLimitContactMsg:
      "Please contact us to purchase or request an additional branch limit.",
    businessLedgerTitle: "Business Ledger",
    businessLedgerShort: "Business Ledger",
    subscriptionLedgerTitle: "Subscription Ledger",
    subscriptionLedgerShort: "Subscription Ledger",
    ledgerAmountLabel: "Amount",
    ledgerEmpty: "No records in this ledger yet.",
  },
};

function getInitialLang() {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored === "tr" || stored === "en") return stored;
  } catch {
    /* ignore */
  }
  return "tr";
}

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(getInitialLang);

  const setLang = useCallback((next) => {
    const value = next === "en" ? "en" : "tr";
    setLangState(value);
    try {
      localStorage.setItem(STORAGE_KEY, value);
    } catch {
      /* ignore */
    }
    document.documentElement.lang = value;
  }, []);

  const toggleLang = useCallback(() => {
    setLangState((prev) => {
      const next = prev === "tr" ? "en" : "tr";
      try {
        localStorage.setItem(STORAGE_KEY, next);
      } catch {
        /* ignore */
      }
      document.documentElement.lang = next;
      return next;
    });
  }, []);

  const t = useCallback(
    (key) => {
      const dict = dictionaries[lang] || dictionaries.tr;
      return dict[key] ?? dictionaries.tr[key] ?? key;
    },
    [lang]
  );

  const value = useMemo(
    () => ({
      lang,
      setLang,
      toggleLang,
      t,
      dict: dictionaries[lang] || dictionaries.tr,
    }),
    [lang, setLang, toggleLang, t]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
