import { createContext, useCallback, useContext, useMemo, useState } from "react";

const LanguageContext = createContext(null);

const STORAGE_KEY = "finsight-lang";

export const dictionaries = {
  tr: {
    liveMarket: "Canlı Piyasa",
    businessLogin: "İşletme Girişi",
    businessPanel: "İşletme Paneli",
    adminPanel: "Admin Paneli",
    logout: "Çıkış Yap",
    partnership: "Partnerlik",
    marketSummary: "Piyasa Özeti",
    marketSummaryNote: "KKTC Merkez Bankası kurları baz alınarak yapılmıştır.",
    searchBanks: "Döviz bürosu ara...",
    openNow: "Şu An Açık",
    currencyConverter: "Döviz Çevirici",
    depositCalculator: "Mevduat Getiri Hesaplayıcı",
    loanCalculator: "Kredi Taksit Hesaplayıcı",
    currencyUnit: "Döviz Birimi",
    selectCurrency: "Döviz Seçiniz",
    operationType: "İşlem Türü",
    buy: "Alış",
    sell: "Satış",
    selectBank: "Döviz Bürosu Seç",
    selectBankPlaceholder: "Bir döviz bürosu seçin",
    amountTl: "Tutar (TL)",
    amountCurrency: "Tutar",
    resultBuy: "Alınacak",
    resultSell: "Elde Edilecek TL",
    resultWaiting: "Sonuç bekleniyor",
    sortLabel: "Sıralama",
    banksLoading: "Kur listesi yukleniyor veya baglanti hatası...",
    noBanksMatch: "Filtrelere uyan işletme bulunamadı.",
    themeLight: "Açık tema",
    themeDark: "Koyu tema",
    langTr: "TR",
    langEn: "EN",
    sortNearest: "En Yakın",
    sortNone: "Sıralama Yok",
    sortGbpBuyHigh: "En Yüksek Alış (GBP)",
    sortGbpBuyLow: "En Düşük Alış (GBP)",
    sortUsdBuyHigh: "En Yüksek Alış (USD)",
    sortUsdBuyLow: "En Düşük Alış (USD)",
    sortEurBuyHigh: "En Yüksek Alış (EUR)",
    sortEurBuyLow: "En Düşük Alış (EUR)",
    periodHourly: "Saatlik",
    periodDaily: "Günlük",
    periodWeekly: "Haftalık",
    periodMonthly: "Aylık",
    periodYearly: "Yıllık",
    backToDashboard: "Dashboard",
    managementPanel: "Yönetim Paneli",
    lastUpdate: "Son Güncelleme",
    subscriptionStatus: "Abonelik Durumu",
    remainingSubscription: "Kalan Abonelik Süresi",
    subscriptionExpired: "Süresi Bitti",
    daysUnit: "Gün",
    centralBankRates: "Merkez Bankası Kurları (Salt Okunur)",
    centralBankRatesNote: "Aşağıdaki kurlar KKTC Merkez Bankası XML kaynağından gelmektedir.",
    subscriptionExpiredNotice:
      "Abonelik süreniz dolmuştur. Kâr marjı ayarları yalnızca görüntülenebilir; güncelleme yapılamaz.",
    buyRates: "ALIŞ KURLAR",
    sellRates: "SATIŞ KURLAR",
    centralBankRate: "Merkez Bankası KUR",
    effectiveRate: "Efektif",
    profitType: "Kâr Tipi",
    profitMargin: "Kâr Marjı",
    profitValue: "Kâr Değeri",
    fixedPrice: "Baz Fiyat (TL)",
    percentPrice: "Yüzdesel (%)",
    finalRate: "Final Kur",
    profitTl: "TL Kâr",
    saveMargins: "Kâr Marjlarını Kaydet",
    saving: "Kaydediliyor...",
    logoutShort: "Çıkış",
    changePassword: "Şifre Değiştir",
    changePasswordTitle: "Şifre Değiştir",
    oldPassword: "Eski Şifre",
    newPassword: "Yeni Şifre",
    confirmPassword: "Yeni Şifre (Tekrar)",
    confirmPasswordAction: "Onayla",
    cancel: "Vazgeç",
    passwordMismatch: "Yeni şifreler eşleşmiyor.",
    passwordChangedSuccess: "Şifre başarıyla değiştirildi.",
    footerTagline: "Kuzey Kıbrıs'ın Döviz Adresi",
    partnershipDesc: "AdaDöviz ile iş ortaklığı kurmak için başvuru formunu doldurun. Biz size ulaşalım.",
    institutionName: "Kurum Adı",
    contactPerson: "Yetkili Kişi",
    emailLabel: "E-posta",
    phoneLabel: "Telefon",
    messageLabel: "Mesaj",
    institutionNamePlaceholder: "Örn: Ada Döviz",
    contactPersonPlaceholder: "Örn: Tuna Gül",
    emailPlaceholder: "partner@kurum.com",
    phonePlaceholder: "+90 5XX XXX XX XX",
    messagePlaceholder: "Sözleşme kapsamı ve talebinizi kısaca belirtin...",
    submitApplication: "Başvuruyu Gönder",
    submitting: "Gönderiliyor...",
    applicationSuccess: "Başvurunuz başarıyla gönderildi. En kısa sürede size dönüş yapacağız.",
    applicationSendFailed: "Gönderme başarısız.",
    businessLoginSubtitle: "Kurum hesabınızla oranlarınızı yönetin",
    usernameLabel: "Kullanıcı Adı",
    usernamePlaceholder: "örn: akbank",
    passwordLabel: "Şifre",
    forgotPassword: "Şifremi Unuttum",
    loginButton: "Giriş Yap",
    loggingIn: "Giriş yapılıyor...",
    loggingInTitle: "Giriş Yapılıyor...",
    loggingInSubtitle: "Yönlendiriliyorsunuz",
    loginFailed: "Giriş başarısız.",
    forgotPasswordTitle: "Şifremi Unuttum",
    forgotPasswordDesc: "Kayıtlı e-posta veya kullanıcı adınızı girin. Sıfırlama bağlantısı gönderilecektir.",
    emailOrUsername: "E-posta / Kullanıcı Adı",
    emailOrUsernamePlaceholder: "ornek@firma.com",
    send: "Gönder",
    sending: "Gönderiliyor...",
    forgotRequestFailed: "İstek gönderilemedi.",
    forgotSuccessDefault: "Eğer bu hesap sistemde kayıtlıysa, şifre sıfırlama bağlantısı e-posta adresinize gönderildi.",
    superAdminTitle: "Super Admin Paneli",
    superAdminSubtitle: "İşletme ve abonelik yönetimi",
    backToDashboardLink: "Dashboard'a Dön",
    logsButton: "Loglar",
    tabList: "Mevcut İşletmeler",
    tabEdit: "İşletme Düzenle & Abonelik",
    tabCreate: "Yeni İşletme Ekle",
    refresh: "Yenile",
    loadingList: "Liste yükleniyor...",
    noBusinessesYet: "Henüz işletme yok.",
    colId: "ID",
    colLoginId: "Giriş ID",
    businessName: "İşletme Adı",
    colSubscription: "Abonelik",
    colRemaining: "Kalan Süre",
    colRegisteredAt: "Kayıt Tarihi",
    colStatus: "Durum",
    colAction: "İşlem",
    statusActive: "Aktif",
    statusInactive: "Pasif",
    editBtn: "Düzenle",
    deleteBtn: "Sil",
    editSubscriptionTitle: "İşletme Düzenle & Abonelik Atama",
    selectFromListPrompt: "Listeden bir işletmenin Düzenle butonuna tıklayın.",
    loginIdEmailField: "Giriş ID / Email",
    newPasswordOptionalField: "Yeni Şifre (boş bırakırsanız değişmez)",
    subscriptionTypeLabel: "ABONELİK TİPİ",
    customDaysLabel: "ÖZEL GÜN (+EKLE / -ÇIKAR)",
    customDaysPlaceholder: "Örn: 15 veya -10",
    currentRemainingLabel: "MEVCUT KALAN",
    afterUpdateLabel: "GÜNCELLEME SONRASI",
    resetSubscriptionBtn: "Aboneliği Sıfırla",
    saveChangesBtn: "Değişiklikleri Kaydet",
    creatingBtn: "Oluşturuluyor...",
    createBusinessBtn: "İşletmeyi Oluştur",
    subTypeTest: "Test",
    subTypeMonthly: "Aylık",
    subTypeYearly: "Yıllık",
    subTypeManual: "Manuel",
    daysRemainingSuffix: "Kaldı",
    minutesAgoSuffix: "dk önce",
    hoursAgoSuffix: "sa önce",
    daysAgoSuffix: "gün önce",
    justNow: "Az önce",
    systemLogsTitle: "Sistem Logları ve İstatistikler",
    totalUniqueVisitors: "Toplam Tekil Ziyaretçi Sayısı",
    recentInteractions: "Son Kullanıcı Etkileşimleri (Anonim)",
    allBusinesses: "Tüm İşletmeler",
    allCurrencies: "Tüm Dövizler",
    allActions: "Tüm Aksiyonlar",
    onlyLocationViewers: "Sadece Konum İnceleyenler",
    onlyCurrencyViewers: "Sadece Kur İnceleyenler",
    onlyBusinessViewers: "Sadece İşletme İnceleyenler",
    noAnonymousSessions: "Henüz anonim oturum kaydı yok.",
    noMatchingRecords: "Filtrelere uyan kayıt bulunamadı.",
    anonymousSession: "Anonim oturum",
    estimatedLocation: "Tahmini Konum:",
    viewedBusinesses: "İncelenen İşletmeler:",
    viewedRates: "Bakılan Kurlar:",
    deleteBusinessTitle: "İşletmeyi Sil",
    deleteConfirmTemplate:
      '"{name}" adlı işletmeyi ve bu işletmeye ait tüm verileri kalıcı olarak silmek istediğinize emin misiniz?',
    deleteWarning: "Dikkat: Bu işlem geri alınamaz!",
    cancelAlt: "İptal",
    confirmDeleteBtn: "Evet, Kalıcı Olarak Sil",
    resetSubConfirmText:
      "Bu işletmenin aboneliğini sıfırlayıp pasif duruma çekmek istediğinize emin misiniz? Bu işlem geri alınamaz.",
    confirmResetBtn: "Evet, Sıfırla",
    successTitle: "Başarılı!",
    okBtn: "Tamam",
    changesAppliedMsg: "Değişiklikler başarıyla uygulandı.",
    businessDeletedMsg: "İşletme kalıcı olarak silindi.",
    subscriptionResetMsg: "Abonelik sıfırlandı; işletme pasife alındı.",
    businessCreatedMsg: "Yeni işletme oluşturuldu.",
    businessUpdatedMsg: "İşletme güncellendi.",
    businessesLoadFailedMsg: "İşletmeler yüklenemedi.",
    statusUpdateFailedMsg: "Durum güncellenemedi.",
    businessDeleteFailedMsg: "İşletme silinemedi.",
    creationFailedMsg: "Oluşturma başarısız.",
    updateFailedMsg: "Güncelleme başarısız.",
    resetFailedMsg: "Sıfırlama başarısız.",
    expiredCantActivateMsg: "Süresi bitmiş işletme aktif edilemez. Önce abonelik süresini uzatın.",
    selectFromListFirstMsg: "Önce listeden bir işletme seçin.",
    statsLoadFailedMsg: "İstatistikler alınamadı.",
    activeToggleInactive: "Aktif — pasife al",
    inactiveToggleActive: "Pasif — aktife al",
    expiredToggleTitle: "Süresi bitmiş — önce abonelik süresini uzatın",
    logoUrlFieldNote: "",
    customerLabel: "Müşteri",
    businessWord: "İşletme",
    dateRangeLabel: "Tarih Aralığı",
    dateFromLabel: "Başlangıç",
    dateToLabel: "Bitiş",
    selectBusinessFilter: "İşletme Seçimi",
    actionTypeLabel: "İşlem Tipi",
    actionTypeProfile: "Profil Güncelleme",
    actionTypeMargin: "Kâr Marjı Güncelleme",
    actionTypeBranch: "Şube Yönetimi",
    businessLogsSectionTitle: "İşletme İşlem Kayıtları",
    businessLogsEmpty: "Filtrelere uyan işletme logu bulunamadı.",
    loadingGeneric: "Yükleniyor...",
  },
  en: {
    liveMarket: "Live Market",
    businessLogin: "Business Login",
    businessPanel: "Business Panel",
    adminPanel: "Admin Panel",
    logout: "Log Out",
    partnership: "Partnership",
    marketSummary: "Market Summary",
    marketSummaryNote: "Based on Central Bank of Northern Cyprus rates.",
    searchBanks: "Search exchange offices...",
    openNow: "Open Now",
    currencyConverter: "Currency Converter",
    depositCalculator: "Deposit Return Calculator",
    loanCalculator: "Loan Installment Calculator",
    currencyUnit: "Currency",
    selectCurrency: "Select Currency",
    operationType: "Operation",
    buy: "Buy",
    sell: "Sell",
    selectBank: "Select Exchange Office",
    selectBankPlaceholder: "Select an exchange office",
    amountTl: "Amount (TRY)",
    amountCurrency: "Amount",
    resultBuy: "You get",
    resultSell: "You get TRY",
    resultWaiting: "Waiting for result",
    sortLabel: "Sort",
    banksLoading: "Loading rates or connection error...",
    noBanksMatch: "No businesses match the filters.",
    themeLight: "Light theme",
    themeDark: "Dark theme",
    langTr: "TR",
    langEn: "EN",
    sortNearest: "Nearest",
    sortNone: "No Sorting",
    sortGbpBuyHigh: "Highest Buy (GBP)",
    sortGbpBuyLow: "Lowest Buy (GBP)",
    sortUsdBuyHigh: "Highest Buy (USD)",
    sortUsdBuyLow: "Lowest Buy (USD)",
    sortEurBuyHigh: "Highest Buy (EUR)",
    sortEurBuyLow: "Lowest Buy (EUR)",
    periodHourly: "Hourly",
    periodDaily: "Daily",
    periodWeekly: "Weekly",
    periodMonthly: "Monthly",
    periodYearly: "Yearly",
    backToDashboard: "Dashboard",
    managementPanel: "Management Panel",
    lastUpdate: "Last Update",
    subscriptionStatus: "Subscription Status",
    remainingSubscription: "Remaining Subscription",
    subscriptionExpired: "Expired",
    daysUnit: "Days",
    centralBankRates: "Central Bank Rates (Read-only)",
    centralBankRatesNote: "The rates below are sourced from the TRNC Central Bank XML feed.",
    subscriptionExpiredNotice:
      "Your subscription has expired. Margin settings are view-only and cannot be updated.",
    buyRates: "BUY RATES",
    sellRates: "SELL RATES",
    centralBankRate: "Central Bank Rate",
    effectiveRate: "Effective",
    profitType: "Profit Type",
    profitMargin: "Profit Margin",
    profitValue: "Profit Value",
    fixedPrice: "Fixed (TRY)",
    percentPrice: "Percent (%)",
    finalRate: "Final Rate",
    profitTl: "TRY Profit",
    saveMargins: "Save Profit Margins",
    saving: "Saving...",
    logoutShort: "Log Out",
    changePassword: "Change Password",
    changePasswordTitle: "Change Password",
    oldPassword: "Current Password",
    newPassword: "New Password",
    confirmPassword: "Confirm New Password",
    confirmPasswordAction: "Confirm",
    cancel: "Cancel",
    passwordMismatch: "New passwords do not match.",
    passwordChangedSuccess: "Password changed successfully.",
    footerTagline: "Northern Cyprus's Currency Address",
    partnershipDesc: "Fill out the application form to become a partner with AdaDöviz. We'll get in touch with you.",
    institutionName: "Institution Name",
    contactPerson: "Contact Person",
    emailLabel: "Email",
    phoneLabel: "Phone",
    messageLabel: "Message",
    institutionNamePlaceholder: "e.g. Ada Döviz",
    contactPersonPlaceholder: "e.g. Tuna Gül",
    emailPlaceholder: "partner@company.com",
    phonePlaceholder: "+90 5XX XXX XX XX",
    messagePlaceholder: "Briefly describe your request and scope of partnership...",
    submitApplication: "Submit Application",
    submitting: "Submitting...",
    applicationSuccess: "Your application has been submitted successfully. We'll get back to you shortly.",
    applicationSendFailed: "Submission failed.",
    businessLoginSubtitle: "Manage your rates with your business account",
    usernameLabel: "Username",
    usernamePlaceholder: "e.g. akbank",
    passwordLabel: "Password",
    forgotPassword: "Forgot Password",
    loginButton: "Log In",
    loggingIn: "Logging in...",
    loggingInTitle: "Logging In...",
    loggingInSubtitle: "You are being redirected",
    loginFailed: "Login failed.",
    forgotPasswordTitle: "Forgot Password",
    forgotPasswordDesc: "Enter your registered email or username. A reset link will be sent.",
    emailOrUsername: "Email / Username",
    emailOrUsernamePlaceholder: "example@company.com",
    send: "Send",
    sending: "Sending...",
    forgotRequestFailed: "Request failed.",
    forgotSuccessDefault: "If this account is registered in the system, a password reset link has been sent to your email.",
    superAdminTitle: "Super Admin Panel",
    superAdminSubtitle: "Business & subscription management",
    backToDashboardLink: "Back to Dashboard",
    logsButton: "Logs",
    tabList: "Current Businesses",
    tabEdit: "Edit Business & Subscription",
    tabCreate: "Add New Business",
    refresh: "Refresh",
    loadingList: "Loading list...",
    noBusinessesYet: "No businesses yet.",
    colId: "ID",
    colLoginId: "Login ID",
    businessName: "Business Name",
    colSubscription: "Subscription",
    colRemaining: "Remaining Time",
    colRegisteredAt: "Registration Date",
    colStatus: "Status",
    colAction: "Action",
    statusActive: "Active",
    statusInactive: "Inactive",
    editBtn: "Edit",
    deleteBtn: "Delete",
    editSubscriptionTitle: "Edit Business & Assign Subscription",
    selectFromListPrompt: "Click the Edit button of a business from the list.",
    loginIdEmailField: "Login ID / Email",
    newPasswordOptionalField: "New Password (leave blank to keep unchanged)",
    subscriptionTypeLabel: "SUBSCRIPTION TYPE",
    customDaysLabel: "CUSTOM DAYS (+ADD / -SUBTRACT)",
    customDaysPlaceholder: "e.g. 15 or -10",
    currentRemainingLabel: "CURRENT REMAINING",
    afterUpdateLabel: "AFTER UPDATE",
    resetSubscriptionBtn: "Reset Subscription",
    saveChangesBtn: "Save Changes",
    creatingBtn: "Creating...",
    createBusinessBtn: "Create Business",
    subTypeTest: "Test",
    subTypeMonthly: "Monthly",
    subTypeYearly: "Yearly",
    subTypeManual: "Manual",
    daysRemainingSuffix: "Left",
    minutesAgoSuffix: "min ago",
    hoursAgoSuffix: "hr ago",
    daysAgoSuffix: "days ago",
    justNow: "Just now",
    systemLogsTitle: "System Logs & Statistics",
    totalUniqueVisitors: "Total Unique Visitors",
    recentInteractions: "Recent User Interactions (Anonymous)",
    allBusinesses: "All Businesses",
    allCurrencies: "All Currencies",
    allActions: "All Actions",
    onlyLocationViewers: "Location Viewers Only",
    onlyCurrencyViewers: "Rate Viewers Only",
    onlyBusinessViewers: "Business Viewers Only",
    noAnonymousSessions: "No anonymous session records yet.",
    noMatchingRecords: "No records match the filters.",
    anonymousSession: "Anonymous session",
    estimatedLocation: "Estimated Location:",
    viewedBusinesses: "Businesses Viewed:",
    viewedRates: "Rates Viewed:",
    deleteBusinessTitle: "Delete Business",
    deleteConfirmTemplate:
      'Are you sure you want to permanently delete the business "{name}" and all of its data?',
    deleteWarning: "Warning: This action cannot be undone!",
    cancelAlt: "Cancel",
    confirmDeleteBtn: "Yes, Delete Permanently",
    resetSubConfirmText:
      "Are you sure you want to reset this business's subscription and set it to inactive? This action cannot be undone.",
    confirmResetBtn: "Yes, Reset",
    successTitle: "Success!",
    okBtn: "OK",
    changesAppliedMsg: "Changes applied successfully.",
    businessDeletedMsg: "Business permanently deleted.",
    subscriptionResetMsg: "Subscription reset; business set to inactive.",
    businessCreatedMsg: "New business created.",
    businessUpdatedMsg: "Business updated.",
    businessesLoadFailedMsg: "Failed to load businesses.",
    statusUpdateFailedMsg: "Failed to update status.",
    businessDeleteFailedMsg: "Failed to delete business.",
    creationFailedMsg: "Creation failed.",
    updateFailedMsg: "Update failed.",
    resetFailedMsg: "Reset failed.",
    expiredCantActivateMsg: "An expired business cannot be activated. Extend the subscription first.",
    selectFromListFirstMsg: "Select a business from the list first.",
    statsLoadFailedMsg: "Failed to load statistics.",
    activeToggleInactive: "Active — deactivate",
    inactiveToggleActive: "Inactive — activate",
    expiredToggleTitle: "Expired — extend the subscription first",
    logoUrlFieldNote: "",
    customerLabel: "Customer",
    businessWord: "Business",
    dateRangeLabel: "Date Range",
    dateFromLabel: "From",
    dateToLabel: "To",
    selectBusinessFilter: "Select Business",
    actionTypeLabel: "Action Type",
    actionTypeProfile: "Profile Update",
    actionTypeMargin: "Profit Margin Update",
    actionTypeBranch: "Branch Management",
    businessLogsSectionTitle: "Business Activity Logs",
    businessLogsEmpty: "No business logs match the filters.",
    loadingGeneric: "Loading...",
  },
};

function getInitialLang() {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored === "tr" || stored === "en") return stored;
  } catch {
    /* ignore */
  }
  return "tr";
}

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(getInitialLang);

  const setLang = useCallback((next) => {
    const value = next === "en" ? "en" : "tr";
    setLangState(value);
    try {
      localStorage.setItem(STORAGE_KEY, value);
    } catch {
      /* ignore */
    }
    document.documentElement.lang = value;
  }, []);

  const toggleLang = useCallback(() => {
    setLangState((prev) => {
      const next = prev === "tr" ? "en" : "tr";
      try {
        localStorage.setItem(STORAGE_KEY, next);
      } catch {
        /* ignore */
      }
      document.documentElement.lang = next;
      return next;
    });
  }, []);

  const t = useCallback(
    (key) => {
      const dict = dictionaries[lang] || dictionaries.tr;
      return dict[key] ?? dictionaries.tr[key] ?? key;
    },
    [lang]
  );

  const value = useMemo(
    () => ({
      lang,
      setLang,
      toggleLang,
      t,
      dict: dictionaries[lang] || dictionaries.tr,
    }),
    [lang, setLang, toggleLang, t]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
